'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Babel=require('@babel/standalone');
let slots=[],index=0,writes=[];
const React={Fragment:'fragment',useState(init){const i=index++;if(!(i in slots))slots[i]=typeof init==='function'?init():init;return[slots[i],v=>slots[i]=typeof v==='function'?v(slots[i]):v]},useMemo(fn){index++;return fn()},useEffect(){},createElement(type,props,...children){return{type,props:props||{},children}}};
const boundary=function Boundary(){};
const archive={leagueName:'Historical league name',championshipHistory:[{year:2015,winner:'Historical champion with full owner name',winnerScore:118.2,loser:'Former owner name',loserScore:87.5,hsp:{offense:{name:'A long historical player name',points:28.3}}}],standings:[{team:'Former franchise',wins:100,losses:88,winPct:53.2,championships:2,playoffs:4,isDefunct:true}],customAwards:[{name:'Archive award',winners:[{year:2015,winner:'Former owner',stats:'Shared archive source'}]}],allTimeTeam:[{pos:'WR',name:'Long all-time player name',team:'CHI',year:2015,points:28.3}]};
const root={App:{},WR:{useViewport:()=>({isPhone:true}),HeroCard:boundary,AssetRow:boundary,CardList:boundary,MobileSection:boundary},CupHonours:boundary,wrIsPro:()=>false};
const ctx={window:root,React,console,localStorage:{getItem:key=>key.startsWith('wr_chronicles_')?JSON.stringify(archive):null,setItem:(...args)=>writes.push(args)},wrAlpha:c=>c};vm.createContext(ctx);vm.runInContext(Babel.transform(fs.readFileSync('js/tabs/trophy-room.js','utf8'),{presets:['react']}).code,ctx);
const walk=n=>n==null||typeof n==='boolean'?[]:Array.isArray(n)?n.flatMap(walk):typeof n==='object'?[n,...walk(n.children)]:[n];const text=n=>walk(n).filter(x=>typeof x!=='object').join('');const find=(tree,pred)=>walk(tree).find(n=>typeof n==='object'&&pred(n));
const props={currentLeague:{league_id:'fixture',season:2026,name:'Fixture'},myRoster:{roster_id:1},playersData:{},initialView:'chronicles'};function render(){index=0;return ctx.TrophyRoomTab(props)}
let tree=render();assert.equal(walk(tree).filter(n=>n.type==='details'&&n.props.className==='la-disclosure').length,4);for(const content of ['Historical champion with full owner name','Former owner name','A long historical player name','Long all-time player name','Shared archive source'])assert(text(tree).includes(content));
const select=find(tree,n=>n.type==='select');assert(text(select).includes('Chronicles'));assert(text(select).includes('Cup history'));select.props.onChange({target:{value:'cup'}});tree=render();assert(find(tree,n=>n.type===boundary&&n.props.league?.league_id==='fixture'),'Cup history receives league identity');
find(tree,n=>n.type==='select').props.onChange({target:{value:'import'}});tree=render();assert(find(tree,n=>n.type==='textarea'));assert.equal(writes.length,0,'Browsing historical views does not alter imported history');
console.log('PASS imported phone history disclosures, complete names/provenance, view selection, import reachability and no browsing writes');
