'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ctx = { window: { App: {}, S: {} } };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('js/shared/weekly-proj.js', 'utf8'), ctx);
const W = ctx.window.App.WeeklyProj;
const scoring = { rec: 0.5, rec_yd: 0.1, rush_yd: 0.1, rec_fd: 0.25, kr_yd: 0.04, st_tkl_solo: 0.75, fum_lost: -0.5 };
// Badie's Week 2 raw line, while absent from prior fantasy roster history.
const raw = { 1: { zero: { gp: 1 }, negative: { gp: 1, fum_lost: 2 }, starter: { gp: 1, rec: 1 }, idle: { gms_active: 1, pos_rank_ppr: 999 } },
    2: { '8208': { gp: 1, rec: 2, rec_yd: 28, rush_yd: 1, rec_fd: 1, kr_yd: 84, st_tkl_solo: 1 }, zero: { gp: 1 }, negative: { gp: 1 }, starter: { gp: 1, rec: 2 } } };
const matchups = { 1: [{ players_points: { zero: 0, negative: -1, starter: 12.34, idle: 0 } }], 2: [{ players_points: { zero: 0, negative: 0, starter: 16.78, idle: 0 } }] };
const requests = [];
const fetcher = async url => { requests.push(url); const week = Number(url.split('/').pop()); return { ok: true, json: async () => url.includes('/matchups/') ? matchups[week] : raw[week] }; };
const options = { leagueId: 'league', season: 2026, throughWeek: 2, scoring, fetcher };
(async () => {
    const history = await W.loadWeeklyPoints(options);
    assert.equal(history.points[2]['8208'], 8.26, 'pickup history includes custom return / special-teams scoring');
    assert.equal(history.points[1].starter, 12.34, 'platform actuals take precedence');
    assert.equal(history.points[1].idle, undefined, 'active-but-did-not-play is not a zero-point game');
    assert.equal(history.points[1].zero, 0, 'played zero is retained');
    assert(requests.every(url => !url.endsWith('/3')), 'current pregame week is never loaded into recent form');
    ctx.window.S = { currentLeagueId: 'league', season: 2026, currentWeek: 3, weeklyPlayerPointsLeagueId: 'league', weeklyPlayerPointsSeason: 2026, weeklyPlayerPointsThroughWeek: 2, weeklyPlayerPoints: history.points, weeklyPlayerPlayed: history.played };
    assert.equal(W.formStats('8208', 5).rollingPPG, 8.3);
    assert.equal(W.formStats('8208', 5).recentCount, 1);
    assert.equal(W.formStats('negative', 5).rollingPPG, -0.5, 'negative and zero games both contribute');
    assert.equal(W.formStats('negative', 1).rollingPPG, 0, 'last game can be a genuine zero');
    assert.equal(W.formStats('negative', 'season').low, -1);
    assert.equal(W.recentPPG('negative', 3, 3), -0.5);
    assert.equal(W.formStats('idle', 5), null);
    assert.equal(W.formStats('missing', 5), null);
    history.points[3] = { '8208': 0 };
    history.points[1].invalid = 'not-a-number';
    history.points[2].invalid = null;
    assert.equal(W.formStats('8208', 5).rollingPPG, 8.3);
    assert.equal(W.formStats('invalid', 5), null);
    ctx.window.S.currentLeagueId = 'other';
    assert.equal(W.formStats('8208', 5), null, 'old league history cannot leak');
    ctx.window.S.currentLeagueId = 'league'; ctx.window.S.season = 2027;
    assert.equal(W.formStats('8208', 5), null, 'old season history cannot leak');
    assert.equal(W.weeklyPointsScope('league',2026,{rec:1,rush_yd:0.1}), W.weeklyPointsScope('league',2026,{rush_yd:0.1,rec:1}));
    assert.notEqual(W.weeklyPointsScope('league',2026,{rec:1}), W.weeklyPointsScope('league',2026,{rec:0.5}));
    const failure = await W.loadWeeklyPoints({ ...options, previousPoints: history.points, previousPlayed: history.played, fetcher: async () => { throw Error('offline'); } });
    assert.equal(failure.complete, false);
    assert.equal(failure.points[2]['8208'], 8.26, 'network failure preserves last good data');
    const partial = await W.loadWeeklyPoints({ ...options, previousPoints: history.points, previousPlayed: history.played, fetcher: async url => url.includes('/stats/') ? { ok: false } : fetcher(url) });
    assert.equal(partial.points[2]['8208'], 8.26, 'missing raw stats cannot erase a pickup history');
    assert.equal(partial.complete, false);
    const noMatchups = await W.loadWeeklyPoints({ ...options, previousPoints: history.points, previousPlayed: history.played, fetcher: async url => url.includes('/matchups/') ? { ok: false } : fetcher(url) });
    assert.equal(noMatchups.points[1].starter, 12.34, 'raw fallback must not overwrite a saved platform actual during a matchup outage');
    const empty = await W.loadWeeklyPoints({ ...options, throughWeek: 0, fetcher: async () => { throw Error('should not fetch'); } });
    assert.equal(Object.keys(empty.points).length, 0);
    console.log('PASS weekly form: Badie pickup history, exact league scoring, played zero/negative games, unavailable data, pregame exclusion, scope isolation and failed-refresh retention');
})().catch(error => { console.error(error); process.exitCode = 1; });
