/* global React */
(function(){
    'use strict';
    const {useState,useEffect,useRef,useMemo}=React;
    const App=window.App, Engine=App.DuatCampaign, Rules=App.DuatRules, Store=App.DuatStorage, Presentation=App.DuatPresentation, Factions=App.DuatWorld.FACTIONS;
    const base=(window.location.pathname.includes('/dist-preview/')?'../':'');
    const asset=path=>base+path;
    const n=value=>Number(value||0).toFixed(1);
    const factionName=Presentation.nameOf;
    let dataPromise;
    async function loadData(){
        if(!dataPromise)dataPromise=Promise.all(['player-cards.json','nflverse-game-logs.csv','manifest.json'].map(async file=>{
            const response=await fetch(asset('data/duat/'+file));
            if(!response.ok)throw new Error('The historical archive could not load. Check your connection and try again.');
            return file.endsWith('.csv')?response.text():response.json();
        })).then(([cards,csv,manifest])=>({cards:App.TimeLeaguePlayerCards.buildPlayerCardIndex(cards),logIndex:App.TimeLeagueSeason.buildGameLogIndex(App.TimeLeagueSeason.parseGameLogCsv(csv).logs),manifest})).catch(error=>{dataPromise=null;throw error;});
        return dataPromise;
    }
    function exportSave(campaign){
        const blob=new Blob([JSON.stringify(campaign,null,2)],{type:'application/json'}), url=URL.createObjectURL(blob);
        const a=document.createElement('a');a.href=url;a.download='duat-'+campaign.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
    }
    const {Sigil,World,Tournaments}=Presentation;
    function GameDay({campaign,factionId,resultWeek,initialClock=0,onProgress,guided=false}){
        const weeks=campaign.completedWeeks;
        const [week,setWeek]=useState(resultWeek||weeks.at(-1)?.week||1), [clock,setClock]=useState(initialClock),[playing,setPlaying]=useState(guided&&initialClock<60),[duration,setDuration]=useState(60);
        useEffect(()=>{setWeek(resultWeek||weeks.at(-1)?.week||1);setClock(initialClock);setPlaying(guided&&initialClock<60);},[campaign.id,campaign.dynastySeason,resultWeek,guided?0:weeks.length]);
        const progressRef=useRef(onProgress);progressRef.current=onProgress;
        useEffect(()=>{if(guided)progressRef.current?.(clock);},[clock,guided]);
        const snapshot=weeks.find(w=>w.week===week);
        const timeline=useMemo(()=>snapshot?App.TimeLeagueGamecast.buildGamecast({seed:campaign.id,week,scoring:campaign.scoring,results:snapshot.factions.map(f=>({teamId:f.factionId,total:f.total,starters:f.players.filter(p=>p.starter).map(p=>({entryId:p.id,name:p.name,points:p.effectivePoints,stats:p.stats||App.TimeLeagueSeason.emptyStatLine(),factor:1}))}))}):null,[campaign.id,snapshot,week]);
        useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setClock(value=>Math.min(60,value+60/duration/5)),200);return()=>clearInterval(timer);},[playing,duration]);
        useEffect(()=>{if(clock>=60)setPlaying(false);},[clock]);
        if(!snapshot)return <section className="duat-panel"><h2>Game day awaits</h2><p>Set your starting lineup, then play Week 1 to watch the historical results unfold.</p></section>;
        const seen=timeline.events.filter(e=>e.t<=clock), totals={};seen.forEach(e=>{totals[e.teamId]=(totals[e.teamId]||0)+e.points;});
        if(clock>=60)snapshot.factions.forEach(f=>{totals[f.factionId]=f.total;});
        const leaders=[...snapshot.factions].sort((a,b)=>(totals[b.factionId]||0)-(totals[a.factionId]||0));
        const my=snapshot.factions.find(f=>f.factionId===factionId);
        const feed=seen.filter(e=>e.teamId===factionId).slice(-8).reverse();
        return <div className="duat-two-column"><section className="duat-panel"><div className="duat-panel-heading"><div><span className="duat-eyebrow">HISTORICAL REPLAY</span><h2>{App.TimeLeagueGamecast.clockLabel(clock)}</h2></div>{!guided&&<label>Week <select aria-label="Replay week" value={week} onChange={e=>{setWeek(Number(e.target.value));setClock(0);setPlaying(false);}}>{weeks.map(w=><option key={w.week} value={w.week}>{w.week}</option>)}</select></label>}</div>
            <div className="duat-score-hero"><Sigil id={factionId}/><div><span>{factionName(factionId)} · {my.season} army</span><strong>{n(totals[factionId])}</strong><span>fantasy points</span></div></div>
            <div className="duat-replay-track"><div style={{width:clock/60*100+'%'}}/></div>
            <div className="duat-actions"><button className="duat-button primary" onClick={()=>{if(clock>=60)setClock(0);setPlaying(!playing);}}>{clock>=60?'Replay':playing?'Pause':'Play'}</button><button className="duat-button" onClick={()=>{setPlaying(false);setClock(Math.min(60,Math.floor(clock/15+1)*15));}}>Next quarter</button>{!guided&&<button className="duat-button" onClick={()=>{setClock(60);setPlaying(false);}}>Final</button>}<select aria-label="Replay duration" value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={60}>1 minute</option><option value={180}>3 minutes</option><option value={300}>5 minutes</option></select></div>
            <p className="duat-muted">Real weekly statistics. Watch the action unfold, or move straight to the weekly result.</p>
            <div className="duat-feed" aria-live="off">{feed.length?feed.map((e,i)=><div key={i}><span>{e.description}</span><strong>{e.points>=0?'+':''}{n(e.points)}</strong></div>):<p>Kickoff · your army is taking the field.</p>}</div>
            {clock>=60&&(campaign.version===4?<section className="duat-score-receipts"><span className="duat-eyebrow">THE FINAL ACCOUNT</span><div className="duat-score-equation"><span><strong>{n(my.baseTotal)}</strong>Football</span><b>+</b><span><strong>{n(my.players.filter(p=>p.starter).reduce((sum,p)=>sum+p.effectivePoints-p.basePoints,0))}</strong>Player favors</span><b>+</b><span><strong>{n(my.teamAdjustment)}</strong>Team ritual</span><b>=</b><span><strong>{n(my.total)}</strong>Final score</span></div>{(my.favors||[]).map((event,index)=>{const player=my.players.find(p=>p.id===event.playerId);return <article key={event.id||index}><div><strong>{event.name||App.DuatRituals.CATALOG.find(f=>f.id===event.ritualId)?.name||(event.ritualId==='ebisu-result'?'Ebisu’s Gamble':'Divine receipt')}</strong>{player&&<span>{player.name}</span>}</div><p>{event.ritualId==='ebisu-result'?`${event.success?'The wager succeeds':'The wager is lost'} · d20 ${event.roll} · ${n(event.beforePoints)} → ${n(event.afterPoints)} team points.`:event.status==='applied'?`${n(event.beforePoints)} → ${n(event.afterPoints)} points${event.sourceWeek?' · recalled from Week '+event.sourceWeek:''}.`:event.reason||event.message}</p><small>{event.cost||0} favor spent{event.status==='unavailable'?' · the offering was not charged':''}</small></article>;})}<p className="duat-muted">{my.favorCost} favor spent this week · {my.favorBalance} remains. {campaign.expansionSettings.heptad.favorPoints?'Player favor points count toward the alliance; team rituals stay with the faction.':'Heptad uses the original football points.'}</p></section>:my.favor&&<p className="duat-notice">{my.favor.status==='applied'?my.favor.name+' applied · '+my.favor.cost+' favor spent':my.favor.reason+' No favor spent.'}</p>)}
        </section><section className="duat-panel"><h2>Around the realm</h2><div className="duat-score-list">{leaders.map((f,i)=><div key={f.factionId} className={f.factionId===factionId?'is-mine':''}><span>{i+1}</span><Sigil id={f.factionId}/><span>{factionName(f.factionId)}</span><strong>{n(totals[f.factionId])}</strong></div>)}</div></section></div>;
    }
    function CampaignSettings({settings,scoring,onSettings,onScoring,expansionSettings,onExpansionSettings}) {
        const set=(key,value)=>onSettings({...settings,[key]:value});
        const score=(key,value)=>onScoring({...scoring,[key]:value});
        return <section className="duat-rules-editor"><span className="duat-eyebrow">WRITE THE LAWS OF YOUR DYNASTY</span><h2>Campaign rules</h2>
            <div className="duat-settings-grid"><label className="duat-field">League size<select value={settings.leagueSize} onChange={e=>set('leagueSize',Number(e.target.value))}>{[8,10,12,14,16].map(n=><option key={n} value={n}>{n} factions · {n/2} alliances</option>)}</select></label>
            <label className="duat-field">Mummy rosters per faction<select value={settings.mummyCount} onChange={e=>set('mummyCount',Number(e.target.value))}>{[1,2,4,5].map(n=><option key={n} value={n}>{n} {n===1?'army':'armies'}</option>)}</select></label>
            <label className="duat-field">Starting roster<select value={settings.roster} onChange={e=>set('roster',e.target.value)}>{Object.entries(Engine.ROSTERS).map(([id,r])=><option key={id} value={id}>{r.name} · {r.slots.length} starters</option>)}</select></label>
            <label className="duat-field">Bench players per army<select value={settings.bench} onChange={e=>set('bench',Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} bench {n===1?'player':'players'}</option>)}</select></label>
            <label className="duat-field">Playoff field<select value={settings.playoffTeams} onChange={e=>set('playoffTeams',Number(e.target.value))}>{[2,4,6,7,8].map(n=><option key={n} value={n}>Top {n} factions</option>)}</select></label>
            <label className="duat-field">Scoring preset<select aria-label="Scoring preset" value={JSON.stringify(scoring)===JSON.stringify({...Engine.SCORING,reception:0})?'standard':JSON.stringify(scoring)===JSON.stringify(Engine.SCORING)?'half':JSON.stringify(scoring)===JSON.stringify({...Engine.SCORING,reception:1})?'ppr':'custom'} onChange={e=>e.target.value!=='custom'&&onScoring({...Engine.SCORING,reception:{standard:0,half:.5,ppr:1}[e.target.value]})}><option value="standard">Standard · no reception points</option><option value="half">Half PPR</option><option value="ppr">Full PPR</option><option value="custom">Custom scoring</option></select></label></div>
            <p className="duat-muted">{Engine.ROSTERS[settings.roster].slots.join(' · ').replaceAll('SUPER_FLEX','Superflex')} + {settings.bench} bench. Flex accepts RB, WR or TE; Superflex also accepts QB. Each mummy carries a different historical year; the d20 chooses one army with equal odds.</p>
            <details className="duat-custom-scoring"><summary>Customize scoring values</summary><div className="duat-settings-grid">{[['reception','Points per reception',0,2,.25],['passTd','Passing touchdown',0,10,.5],['passingYd','Per passing yard',0,1,.01],['rushRecYd','Per rushing / receiving yard',0,1,.01],['turnover','Interception / lost fumble',-10,0,.5]].map(([key,label,min,max,step])=><label className="duat-field" key={key}>{label}<input type="number" required min={min} max={max} step={step} value={scoring[key]} onChange={e=>score(key,e.target.value===''?'':Number(e.target.value))}/></label>)}</div><p className="duat-muted">Rushing and receiving touchdowns: 6. Two-point conversions: 2. Historical skill players only; no kickers or defenses.</p></details>
            <div className="duat-rule-switches"><label><input type="checkbox" checked={settings.favors} onChange={e=>set('favors',e.target.checked)}/><span><strong>Divine favors</strong><small>Spend your treasury on sacred weeks.</small></span></label><label><input type="checkbox" checked={settings.conquest} onChange={e=>set('conquest',e.target.checked)}/><span><strong>Conquest</strong><small>Claim land, invade rivals and fortify borders.</small></span></label></div>
            {settings.favors&&<label className="duat-field">Starting favor budget per faction<input type="number" required min="0" max="500" step="1" value={settings.favorBudget} onChange={e=>set('favorBudget',e.target.value===''?'':Number(e.target.value))}/><small>0–500 favor for the entire season. The same budget applies to humans and AI.</small></label>}
            <details className="duat-expansion-settings"><summary>Conquest and Heptad options</summary>
                {settings.conquest&&<div className="duat-form-row"><label className="duat-field">World map<select value={expansionSettings.worldScale} onChange={e=>onExpansionSettings({...expansionSettings,worldScale:e.target.value})}><option value="provinces">Province world · local fronts and crossings</option><option value="countries">Country world · 175 territories</option></select></label><label className="duat-field">Conquest rules<select value={expansionSettings.conquestMode} onChange={e=>onExpansionSettings({...expansionSettings,conquestMode:e.target.value})}><option value="combat">Expanded combat · dice and fortifications</option><option value="original">Original conquest · football decides the war</option></select></label></div>}
                <App.DuatHeptadUI.RulesControls value={expansionSettings.heptad} onChange={heptad=>onExpansionSettings({...expansionSettings,heptad})}/>
            </details><p className="duat-muted">Rulers retire after one season. Surviving tombs and conquered land continue into the next dynasty season. Original Duat drafts allow at most two quarterbacks per army.</p>
            <p className="duat-notice">{settings.mummyCount*(Engine.ROSTERS[settings.roster].slots.length+settings.bench)} picks per human · {settings.leagueSize*settings.mummyCount*(Engine.ROSTERS[settings.roster].slots.length+settings.bench)} picks overall. Rules are fixed when the campaign is founded.</p>
        </section>;
    }
    function RulesSummary({campaign}) {
        const rules=Engine.settingsOf(campaign), scoring=campaign.scoring;
        return <details className="duat-panel duat-rules-summary"><summary>Campaign rules · {rules.leagueSize} factions · {Engine.ROSTERS[rules.roster].name} · {scoring.reception} PPR</summary><div className="duat-settings-grid"><div><h3>Football</h3><p>{Engine.ROSTERS[rules.roster].slots.join(' · ').replaceAll('SUPER_FLEX','Superflex')} + {rules.bench} bench.</p><p>{rules.mummyCount} mummy {rules.mummyCount===1?'army':'armies'} per faction · {campaign.seasons.join(', ')}.</p><p>All-play through Week {Engine.regularSeasonWeeks(campaign)}. Top {rules.playoffTeams} qualify; the crown is decided in Week 17.</p></div><div><h3>Scoring</h3><p>{scoring.reception} per reception · {scoring.passTd} per passing TD · {scoring.passingYd} per passing yard · {scoring.rushRecYd} per rushing / receiving yard · {scoring.turnover} per interception / lost fumble.</p><p>Rushing / receiving TD: 6. Two-point conversion: 2.</p></div><div><h3>The realm</h3><p>Favors {rules.favors?'on · '+rules.favorBudget+' starting favor per faction':'off'}. Conquest {rules.conquest?'on':'off'}.</p><p>{rules.leagueSize/2} two-faction alliances. Heptad selects the strongest legal lineup from {campaign.expansionSettings?.heptad.pool==='army'?'both full armies':'both teams’ starters'}, {campaign.expansionSettings?.heptad.favorPoints?'including player favors':'before favors'}. {campaign.expansionSettings?.heptad.duplicates==='unique-athlete'?'Each athlete counts once.':'Different season cards may each count.'}</p></div></div><p className="duat-muted">Rules stay fixed for this campaign. Found a new dynasty to play another format.</p></details>;
    }
    function DuatGame({onClose}){
        const [campaign,setCampaign]=useState(null),[room,setRoom]=useState(null),[data,setData]=useState(null),[shelf,setShelf]=useState([]),[rooms,setRooms]=useState([]);
        const [mode,setMode]=useState(()=>{try{return new URLSearchParams(location.search).has('duat_invite')||sessionStorage.getItem('duat-pending-invite')?'friends':'solo';}catch{return 'solo';}}),[name,setName]=useState('The First Dynasty'),[factionId,setFactionId]=useState('egypt'),[endYear,setEndYear]=useState(2025),[humans,setHumans]=useState(2);
        const [settings,setSettings]=useState(()=>Engine.normalizeSettings()),[scoring,setScoring]=useState({...Engine.SCORING});
        const [expansionSettings,setExpansionSettings]=useState(()=>Engine.expansionOptions({worldScale:"countries"})),[nextYear,setNextYear]=useState(0);
        function changeSettings(next){setSettings(next);if(next.leagueSize!==settings.leagueSize){setHumans(n=>Math.min(n,next.leagueSize));setSelectedFactions(ids=>[...new Set([factionId,...ids,...Factions.map(f=>f.id)])].slice(0,next.leagueSize));}}
        const rules=Engine.settingsOf(campaign);
        const [selectedFactions,setSelectedFactions]=useState(()=>Rules.FACTIONS.map(f=>f.id)),[factionQuery,setFactionQuery]=useState(''),[showExcavation,setShowExcavation]=useState(false);
        const [tab,setTab]=useState('home'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[archiveLoading,setArchiveLoading]=useState(true);
        const [weeklyState,setWeeklyState]=useState(null);
        const [lineup,setLineup]=useState([]),[favorId,setFavorId]=useState('kratos-1'),[target,setTarget]=useState(''),[sourceWeek,setSourceWeek]=useState(1),[removeId,setRemoveId]=useState(null);
        const [invite,setInvite]=useState(()=>{const code=new URLSearchParams(window.location.search).get('duat_invite');try{if(code)sessionStorage.setItem('duat-pending-invite',code);return code||sessionStorage.getItem('duat-pending-invite')||'';}catch{return code||'';}});
        const activeRef=useRef(null),requestRef=useRef(0),fileRef=useRef(null),campaignRef=useRef(null);campaignRef.current=campaign;
        const accountId=App.OD?.getCurrentUserId?.();
        const accountRef=useRef(accountId);
        useEffect(()=>{if(accountRef.current!==accountId){accountRef.current=accountId;requestRef.current++;setRooms([]);setBusy(false);if(activeRef.current){activeRef.current=null;setRoom(null);setCampaign(null);setError('Your account changed. Open a campaign from your own account.');}}},[accountId]);
        const me=room?.self.factionId||campaign?.hostFactionId||factionId;
        const faction=campaign?.factions.find(f=>f.id===me),army=faction&&Engine.activeArmy(faction);
        const ready=Boolean(room?.seats.find(s=>s.factionId===me)?.ready),host=!room||room.self.role==='host';
        const seasons=data?Engine.availableSeasons(data):[];
        const epochs=seasons.filter(year=>Array.from({length:settings.mummyCount},(_,i)=>i).every(offset=>seasons.includes(year-offset)));
        useEffect(()=>{if(epochs.length&&!epochs.includes(endYear))setEndYear(epochs[0]);},[settings.mummyCount,data]);
        const refreshShelf=()=>{try{setShelf(Store.list());}catch(e){setError(e.message);}};
        useEffect(()=>{let alive=true;refreshShelf();loadData().then(value=>{if(alive){setData(value);setEndYear(Engine.availableSeasons(value)[0]);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setArchiveLoading(false);});return()=>{alive=false;};},[]);
        useEffect(()=>{if(!faction)return;setLineup([...faction.lineup]);setTarget(faction.lineup[0]||'');},[campaign?.id,campaign?.week,JSON.stringify(faction?.lineup)]);
        const acceptRoom=(next,opening=false)=>{if(!next)return;const previous=activeRef.current;if(!opening&&(!previous||previous.id!==next.id))return;if(previous&&previous.id===next.id&&next.revision<previous.revision)return;if(!opening&&next.campaign.archaeology?.latest?.factionId&&next.campaign.archaeology.latest.factionId!==previous?.campaign?.archaeology?.latest?.factionId)setShowExcavation(true);activeRef.current=next;setRoom(next);setCampaign(next.campaign);};
        async function listRooms(){if(!accountId){setRooms([]);return;}const user=accountId,generation=requestRef.current;const result=await App.DuatRemote.request({op:'list'});if(user!==App.OD?.getCurrentUserId?.()||generation!==requestRef.current)return;if(result.ok)setRooms(result.rooms||[]);else setError(result.error);}
        useEffect(()=>{if(mode==='friends')listRooms();},[mode,accountId]);
        useEffect(()=>{
            if(!room?.id)return;
            const roomId=room.id, userId=accountId;let alive=true,inflight=false;
            async function refresh(){if(!alive||inflight)return;if(App.OD?.getCurrentUserId?.()!==userId){activeRef.current=null;setRoom(null);setCampaign(null);setError('Your account changed. Reopen your campaign.');return;}inflight=true;
                const result=await App.DuatRemote.request({op:'load',roomId});inflight=false;if(!alive||activeRef.current?.id!==roomId)return;
                if(result.ok)acceptRoom(result.room);else setError(result.error);
            }
            const timer=setInterval(refresh,4000);window.addEventListener('focus',refresh);window.addEventListener('online',refresh);
            return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh);};
        },[room?.id,accountId]);
        async function run(action){
            if(busy||!campaign)return;const generation=requestRef.current,user=accountId,originRoom=room?.id;const valid=()=>generation===requestRef.current&&(!originRoom||activeRef.current?.id===originRoom&&App.OD?.getCurrentUserId?.()===user);setBusy(true);setError('');setNotice('');
            try{
                if(room){const current=activeRef.current;const result=await App.DuatRemote.request({op:'action',roomId:current.id,expectedRevision:current.revision,actionId:crypto.randomUUID(),action:{...action,factionId:me}});
                    if(!valid())return;
                    if(!result.ok){if(result.conflict){const fresh=await App.DuatRemote.request({op:'load',roomId:current.id});if(!valid())return;if(fresh.ok)acceptRoom(fresh.room);}throw new Error(result.error);}
                    acceptRoom(result.room);
                }else{const next=Engine.applyAction(campaignRef.current,{...action,factionId:me,createdAt:new Date().toISOString()},data);Store.write(next);setCampaign(next);refreshShelf();}
                if(action.type==='next-season'){setTab('home');setShowExcavation(false);setNextYear(0);}else if(action.type==='advance-week')setTab('home');else if(action.type==='reveal-next')setShowExcavation(true);else if(action.type==='reveal-rulers')setNotice('Your ruler has returned. Set the starting five for Week 1.');else if(action.type==='set-lineup')setNotice('Starting lineup saved.');else if(action.type==='declare-favor')setNotice('Favor declared for this week.');else if(action.type==='claim')setNotice('Your banner now flies over new land.');else if(action.type==='fortify')setNotice('Defenses strengthened.');
                return true;
            }catch(e){if(valid())setError(e.message);return false;}finally{if(valid())setBusy(false);}
        }
        async function create(event){event.preventDefault();if(busy)return;const generation=++requestRef.current,user=accountId;const valid=()=>generation===requestRef.current&&(mode!=='friends'||user===App.OD?.getCurrentUserId?.());setBusy(true);setError('');
            try{const chosen=Array.from({length:settings.mummyCount},(_,i)=>endYear-i), factionIds=[factionId,...selectedFactions.filter(id=>id!==factionId)], humanFactionIds=mode==='friends'?factionIds.slice(0,humans):[factionId];
                if(mode==='friends'){const result=await App.DuatRemote.request({op:'create',input:{version:4,settings,scoring,expansionSettings,name,seasons:chosen,hostFactionId:factionId,humanFactionIds,factionIds}});if(!valid())return;if(!result.ok)throw new Error(result.error);acceptRoom(result.room,true);}
                else{const next=Engine.createCampaign({version:4,settings,scoring,expansionSettings,id:crypto.randomUUID(),name,seasons:chosen,hostFactionId:factionId,humanFactionIds,factionIds,seed:crypto.randomUUID(),createdAt:new Date().toISOString()},data);Store.write(next);activeRef.current=null;setRoom(null);setCampaign(next);refreshShelf();}
                setTab('home');setShowExcavation(false);
            }catch(e){if(valid())setError(e.message);}finally{if(valid())setBusy(false);}
        }
        async function openOnline(id){setBusy(true);setError('');const request=++requestRef.current,user=accountId;const result=await App.DuatRemote.request({op:'load',roomId:id});if(request!==requestRef.current||user!==App.OD?.getCurrentUserId?.())return false;if(result.ok){activeRef.current=null;acceptRoom(result.room,true);setTab('home');}else setError(result.error);setBusy(false);return Boolean(result.ok);}
        async function join(){const generation=++requestRef.current,user=accountId;setBusy(true);setError('');const result=await App.DuatRemote.request({op:'claim',code:invite.trim()});if(generation!==requestRef.current||user!==App.OD?.getCurrentUserId?.())return;if(result.ok){const opened=await openOnline(result.roomId||result.room?.id);if(!opened)return;try{sessionStorage.removeItem('duat-pending-invite');}catch{}setInvite('');const url=new URL(location.href);url.searchParams.delete('duat_invite');history.replaceState({},'',url);}else{setError(result.error);setBusy(false);}}
        function home(){setShowExcavation(false);requestRef.current++;activeRef.current=null;setCampaign(null);setRoom(null);setBusy(false);setError('');setNotice('');refreshShelf();if(mode==='friends')listRooms();}
        async function restore(file){if(!file)return;const generation=++requestRef.current;setError('');try{if(file.size>25000000)throw new Error('This backup is too large. Choose a Duat campaign backup under 25 MB.');const saved=JSON.parse(await file.text());if(generation!==requestRef.current)return;if(!Engine.validateCampaign(saved))throw new Error('Choose a valid Duat campaign backup.');Store.write(saved);setRoom(null);activeRef.current=null;setCampaign(saved);refreshShelf();setNotice('Campaign restored on this browser.');}catch(e){if(generation===requestRef.current)setError(e.message);}finally{if(fileRef.current)fileRef.current.value='';}}
        const expanded=campaign?.version===4;
        const nextYears=expanded&&campaign.phase==='complete'?(room?campaign.nextSeasonYears||[]:data?Engine.nextSeasonYears(campaign,data):[]):[];
        const recruitPool=expanded&&rules.favors&&['season','complete'].includes(campaign.phase)?(room?campaign.ritualCandidates||[]:data?Engine.ritualCandidates(campaign,data,me):[]):[];
        const recruitPoolLoaded=Boolean(room?Array.isArray(campaign?.ritualCandidates):data);
        const recruitmentPending=Boolean(faction?.rituals?.pendingMahdi);
        const pending=campaign?campaign.conquest.pendingClaims[me]||0:0;
        const requiredClaims=campaign?Engine.unresolvedClaims(campaign):[],waitingClaim=requiredClaims.length>0,ownClaim=requiredClaims.includes(me);
        const warReserve=campaign?.expansionSettings?.conquestMode==='original'?pending:pending+(campaign?.conquest.campaignActions?.[me]||0);
        const legal=Boolean(faction&&Engine.legalLineup(faction,lineup));
        const dirty=Boolean(faction&&JSON.stringify([...lineup].sort())!==JSON.stringify([...faction.lineup].sort()));
        const Progress=App.DuatWeeklyProgress,Flow=App.DuatWeeklyUI;
        const flowActive=Boolean(campaign&&['season','complete'].includes(campaign.phase)&&!showExcavation);
        const flowScope=room?'online:'+accountId:'solo';
        const presentationStorage={getItem:key=>window.localStorage.getItem(key),setItem:(key,value)=>window.localStorage.setItem(key,value)};
        const flowKey=campaign?Progress.key(campaign,me,flowScope):'';
        const progress=campaign?(weeklyState?.key===flowKey?weeklyState.value:Progress.read(campaign,me,presentationStorage,flowScope)):null;
        useEffect(()=>{if(campaign){const value=Progress.normalize(progress,campaign,me);setWeeklyState({key:flowKey,value});try{Progress.write(value,campaign,me,presentationStorage,flowScope);}catch{ /* Presentation remains usable in memory. */ }}},[flowKey,campaign?.week,campaign?.completedWeeks.length]);
        const preparation=flowActive?App.DuatWeeklyFlow.preparation(campaign,me,campaign.week,{ritualCandidates:recruitPool}):null;
        const lineupFingerprint=Progress.fingerprint(faction,lineup);
        const flow=flowActive?Progress.describe(progress,campaign,me,{fingerprint:lineupFingerprint,legal,dirty,pendingMahdi:recruitmentPending,hasFavors:preparation?.hasUsableOptions}):null;
        function moveFlow(event){
            if(!campaign)return;
            const value=Progress.update(progress,campaign,me,event);
            setWeeklyState({key:flowKey,value});
            try{Progress.write(value,campaign,me,presentationStorage,flowScope);}catch{setNotice('Your weekly place is kept for this visit. Browser storage is unavailable; an exported campaign backup still protects your game.');}
            setTab('home');
        }
        const canExplore=Boolean(flow&&flow.stage!=='games'&&flow.caughtUp);
        const exploring=canExplore&&tab!=='home';
        useEffect(()=>{if(flow?.stage==='games')setTab('home');},[flowKey,flow?.stage,flow?.resultWeek]);
        const currentResult=flow?.resultWeek?App.DuatWeeklyFlow.outcome(campaign,me,flow.resultWeek):null;
        const progressClock=clock=>moveFlow({type:'clock',week:flow.resultWeek,clock});
        const finishConquest=()=>moveFlow({type:'conquest-done',week:flow.resultWeek});
        const editLineup=async()=>{if(ready&&!await run({type:'set-ready',ready:false}))return;moveFlow({type:'edit-lineup',week:campaign.week});};
        async function confirmLineup(){if(dirty&&!await run({type:'set-lineup',playerIds:lineup}))return;moveFlow({type:'lineup-confirm',week:campaign.week,fingerprint:lineupFingerprint});}
        const nextLabel=flow&&!flow.caughtUp?'Review Week '+(flow.week+1):campaign?.phase==='complete'?'Continue to season honors':'Prepare Week '+(campaign?.week||1);
        let primary,secondary,flowNote='';
        if(flow?.stage==='alliance')primary={label:'Meet my ally · prepare Week 1',onClick:()=>moveFlow({type:'alliance-seen'})};
        if(flow?.stage==='lineup'){
            primary={label:dirty?'Save and confirm lineup':'Confirm starting lineup',disabled:!legal||ready&&dirty,onClick:confirmLineup};
            flowNote=!legal?'Fill every required starting slot with a different player.':dirty?'Your changes will be saved before you continue.':'Confirm this lineup for Week '+campaign.week+'.';
            if(ready)secondary={label:'Unready to edit lineup',onClick:editLineup};
        }
        if(flow?.stage==='favors'){
            primary={label:recruitmentPending?'Resolve your waiting recruit':'Continue to kickoff',disabled:recruitmentPending||dirty,onClick:()=>moveFlow({type:'favors-done'})};
            secondary={label:'Edit lineup',onClick:editLineup};
            flowNote=recruitmentPending?'Accept or decline the waiting Mahdi recruit before the week can start.':preparation?.preseason?'These preseason rituals are optional and close at kickoff. You can continue without an offering.':'Offerings are optional. Explore any god; dimmed favors explain why they are unavailable.';
        }
        if(flow?.stage==='kickoff'){
            const label=room&&!ready?'Mark ready for Week '+campaign.week:room&&!host?'Waiting for the host':room&&!room.canAdvance?'Waiting for the other factions':'Start Week '+campaign.week+' games';
            primary={label,disabled:!data||dirty||recruitmentPending||waitingClaim||Boolean(room&&ready&&(!host||!room.canAdvance)),onClick:()=>run({type:room&&!ready?'set-ready':'advance-week',...(room&&!ready?{ready:true}:{})})};
            secondary=ownClaim?{label:'Return to your war council',onClick:()=>moveFlow({type:'conquest-reopen',week:campaign.completedWeeks.at(-1)?.week})}:{label:ready?'Unready and edit lineup':'Edit lineup',onClick:editLineup};
            if(waitingClaim)flowNote='The war council is still open for a human faction. Kickoff waits until earned moves are resolved.';
        }
        if(flow?.stage==='games')primary={label:'See Week '+flow.week+' result',onClick:()=>progressClock(60)};
        if(flow?.stage==='recap')primary={label:rules.conquest?'Continue to conquest':nextLabel,onClick:()=>{const value=Progress.update(progress,campaign,me,{type:'recap-done',week:flow.resultWeek});if(rules.conquest)moveFlow({type:'recap-done',week:flow.resultWeek});else{const done=Progress.update(value,campaign,me,{type:'conquest-done',week:flow.resultWeek});setWeeklyState({key:flowKey,value:done});try{Progress.write(done,campaign,me,presentationStorage,flowScope);}catch{setNotice('Weekly progress is kept for this visit.');}}}};
        if(flow?.stage==='conquest')primary={label:flow.caughtUp&&ownClaim?'Choose a highlighted claim':nextLabel,disabled:flow.caughtUp&&ownClaim,onClick:finishConquest};
        const standings=campaign?Engine.computeStandings(campaign):[];
        const last=campaign?.completedWeeks.at(-1);
        const signedIn=Boolean(accountId&&App.OD?.getSessionToken?.());
        return <div className="duat-game"><header className="duat-topbar"><button className="duat-back" onClick={campaign?home:onClose}>← {campaign?'Campaigns':'Dynasty HQ'}</button><span className="duat-wordmark">THE DUAT <small>HISTORICAL</small></span><span className="duat-status">{room?'With friends':campaign?'Solo campaign':'Dynasty HQ Games'}</span></header>
            <main className="duat-main">{error&&<div role="alert" className="duat-alert">{error}<button className="duat-link" onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<p role="status" className="duat-notice">{notice}</p>}
            {!campaign?<><div className="duat-intro" style={{backgroundImage:`linear-gradient(90deg,rgba(12,19,26,.95),rgba(12,19,26,.64) 42%,rgba(12,19,26,.08)),url(${Presentation.art('hero')})`}}><span className="duat-eyebrow">BURIED RULERS. ONE RETURN.</span><h1>Build a dynasty.<br/><em>Conquer the afterlife.</em></h1><p>Twenty-eight factions. Buried rulers, rival empires and twelve gods. Draft your armies, unearth a named ruler, and build a dynasty whose history survives every season.</p></div>
                <div className="duat-setup-grid"><form className="duat-panel" onSubmit={create}><div className="duat-choice-row"><button type="button" className={'duat-choice '+(mode==='solo'?'selected':'')} aria-pressed={mode==='solo'} onClick={()=>setMode('solo')}><strong>Play Solo</strong><span>You and {settings.leagueSize-1} AI factions</span></button><button type="button" className={'duat-choice '+(mode==='friends'?'selected':'')} aria-pressed={mode==='friends'} onClick={()=>setMode('friends')}><strong>Play with Friends</strong><span>Private invites. Advance together.</span></button></div>
                    {mode==='friends'&&!signedIn&&<p className="duat-notice">Sign in with your Dynasty HQ email account to create or join a campaign. <a href={asset('login.html?duat=1')}>Sign in</a></p>}
                    <label className="duat-field">Campaign name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>
                    <div className="duat-form-row"><label className="duat-field">Ruler years<select aria-label="Ruler years" value={endYear} onChange={e=>setEndYear(Number(e.target.value))}>{epochs.map(year=><option key={year} value={year}>{settings.mummyCount===1?year:`${year-settings.mummyCount+1}–${year}`}</option>)}</select></label>{mode==='friends'&&<label className="duat-field">Human factions<select value={humans} onChange={e=>setHumans(Number(e.target.value))}>{Array.from({length:settings.leagueSize-1},(_,i)=>i+2).map(x=><option key={x} value={x}>{x} friends · {settings.leagueSize-x} AI</option>)}</select></label>}</div>
                    <CampaignSettings settings={settings} scoring={scoring} onSettings={changeSettings} onScoring={setScoring} expansionSettings={expansionSettings} onExpansionSettings={setExpansionSettings}/>
                    <label className="duat-field">Choose your faction · 28 banners<input aria-label="Find a faction" placeholder="Search factions or regions…" value={factionQuery} onChange={e=>setFactionQuery(e.target.value)}/></label><fieldset className="duat-faction-picker"><legend>Your banner</legend>{Factions.filter(f=>`${f.name} ${f.region} ${f.realm}`.toLowerCase().includes(factionQuery.toLowerCase())).map(f=><button key={f.id} type="button" className={'duat-faction-choice '+(factionId===f.id?'selected':'')} aria-pressed={factionId===f.id} style={{'--faction-color':f.color}} onClick={()=>{setFactionId(f.id);setSelectedFactions(ids=>ids.includes(f.id)?ids:ids.map(id=>id===factionId?f.id:id));}}><Sigil id={f.id}/><span>{f.name}</span></button>)}</fieldset><details className="duat-rival-picker"><summary>Choose the rival factions · {selectedFactions.length}/{settings.leagueSize} banners</summary><p className="duat-muted">{settings.leagueSize} factions enter this campaign, paired into {settings.leagueSize/2} alliances. Choose the other {settings.leagueSize-1} banners.</p><div>{Factions.map(f=><label key={f.id}><input type="checkbox" checked={selectedFactions.includes(f.id)} disabled={f.id===factionId||selectedFactions.length>=settings.leagueSize&&!selectedFactions.includes(f.id)} onChange={()=>setSelectedFactions(ids=>ids.includes(f.id)?ids.filter(id=>id!==f.id):[...ids,f.id])}/><Sigil id={f.id}/>{f.name}</label>)}</div></details>
                    <button className="duat-button primary duat-wide" disabled={busy||archiveLoading||!data||!name.trim()||selectedFactions.length!==settings.leagueSize||(mode==='friends'&&!signedIn)}>{busy?'Founding your dynasty…':archiveLoading?'Loading the historical archive…':mode==='solo'?'Found a dynasty · enter the draft':'Create friends’ campaign'}</button>
                    {!data&&!archiveLoading&&<button type="button" className="duat-button" onClick={()=>{setArchiveLoading(true);loadData().then(setData).catch(e=>setError(e.message)).finally(()=>setArchiveLoading(false));}}>Retry archive</button>}
                    <p className="duat-muted">Draft your armies, set your lineup and play seventeen historical weeks. Your rules apply to every faction.</p>
                </form><aside className="duat-setup-aside"><div className="duat-faction-banner" style={{'--faction-color':Presentation.identity(factionId)?.color}}><Sigil id={factionId}/><span className="duat-eyebrow">YOUR FACTION</span><h2>{factionName(factionId)}</h2><p>{Presentation.identity(factionId)?.motto}</p><span>{Presentation.identity(factionId)?.realm}</span></div>
                    <section className="duat-panel"><h2>Return to a campaign</h2>{shelf.length?shelf.map(saved=><div className="duat-save-row" key={saved.id}><button className="duat-save-open" onClick={()=>{try{const state=Store.read(saved.id);requestRef.current++;setBusy(false);setCampaign(state);setRoom(null);activeRef.current=null;setTab('home');}catch(e){setError(e.message);}}}><strong>{saved.name}</strong><span>{factionName(saved.factionId)}{saved.dynastySeason?' · Dynasty season '+saved.dynastySeason:''} · {saved.phase==='complete'?'Complete':saved.phase==='preseason'||saved.phase==='reveal'?'Excavation':saved.phase==='draft'?'Draft in progress':'Week '+saved.week}</span></button><button className="duat-link" onClick={()=>{if(removeId===saved.id){try{Store.remove(saved.id);refreshShelf();setRemoveId(null);}catch(e){setError(e.message);}}else setRemoveId(saved.id);}}>{removeId===saved.id?'Confirm delete':'Delete'}</button></div>):<p className="duat-muted">Your solo campaigns will be saved here on this browser.</p>}
                        <button className="duat-button" onClick={()=>fileRef.current.click()}>Restore a backup</button><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={e=>restore(e.target.files[0])}/>
                    </section>{mode==='friends'&&<section className="duat-panel"><h2>Your friends’ campaigns</h2>{rooms.map(saved=><button className="duat-save-open" key={saved.id} disabled={busy} onClick={()=>openOnline(saved.id)}><strong>{saved.name}</strong><span>{saved.phase==='preseason'?'Waiting room':saved.phase==='draft'?'Draft':saved.phase==='reveal'?'Excavation':'Week '+saved.week}</span></button>)}<label className="duat-field">Invitation code<input value={invite} onChange={e=>setInvite(e.target.value)} placeholder="Paste your invitation code"/></label><button className="duat-button" disabled={!invite.trim()||busy||!signedIn} onClick={join}>Join campaign</button></section>}
                </aside></div></>:<><section className="duat-campaign-heading"><div className="duat-campaign-identity"><Sigil id={me}/><div><span className="duat-eyebrow">{campaign.name}</span><h1>{factionName(me)}</h1><p>{army?`${expanded?army.rulerName+' · ':''}${army.season} NFL year · d20 roll ${faction.rulerRoll}`:campaign.phase==='draft'?rules.mummyCount+(rules.mummyCount===1?' army is yours to build.':' armies are yours to build.'):'The buried rulers await your return.'}</p></div></div><div className="duat-campaign-facts"><span><strong>{flow?'Week '+flow.week:campaign.phase==='complete'?'Final':campaign.phase==='preseason'||campaign.phase==='reveal'?'Excavation':campaign.phase==='draft'?'Draft':'Week '+campaign.week}</strong>{(flow?.week||campaign.week)>Engine.regularSeasonWeeks(campaign)&&['season','complete'].includes(campaign.phase)?'Heavenly Battle':expanded?'Dynasty season '+campaign.dynastySeason:'Historical campaign'}</span>{rules.favors&&flow?.stage!=='games'&&flow?.caughtUp!==false&&<span><strong>${faction?.favorBalance??rules.favorBudget}</strong>Favor treasury</span>}{rules.conquest&&flow?.stage!=='games'&&flow?.caughtUp!==false&&<Presentation.Land campaign={campaign} factionId={me} compact/>}</div></section>
                <RulesSummary campaign={campaign}/>
                {room&&!flowActive&&<section className="duat-room-bar"><span>{room.seats.filter(s=>s.controller==='human'&&s.joined).length} of {room.seats.filter(s=>s.controller==='human').length} human factions joined</span><span>{room.seats.filter(s=>s.controller==='human'&&s.ready).length} ready</span>{(campaign.phase!=='complete'||expanded)&&!(campaign.phase==='draft'&&campaign.draft.status==='active')&&!(campaign.phase==='reveal'&&campaign.archaeology.revealedFactionIds.length>0)&&<button className={'duat-button '+(!ready?'primary':'')} disabled={busy||!ready&&(dirty||recruitmentPending||ownClaim)} onClick={()=>run({type:'set-ready',ready:!ready})}>{ready?'Ready · change to unready':'Mark my faction ready'}</button>}<button className="duat-link" onClick={()=>setTab('friends')}>Friends & invites</button></section>}
                {campaign.phase==='draft'?<Presentation.Draft campaign={campaign} factionId={me} data={data} online={Boolean(room)} host={host} canAdvance={!room||room.canAdvance} onAction={run} busy={busy}/>:campaign.phase==='reveal'||showExcavation?<Presentation.Archaeology campaign={campaign} host={host} canAdvance={!room||room.canAdvance} onAction={run} busy={busy} onContinue={()=>{setShowExcavation(false);setTab('home');}}/>:campaign.phase==='preseason'?<section className="duat-panel"><div className="duat-panel-heading"><div><span className="duat-eyebrow">THE RESURRECTION</span><h2>Which ruler will walk again?</h2></div><button className="duat-button primary" disabled={busy||!data||!host||Boolean(room&&!room.canAdvance)} onClick={()=>run({type:'reveal-rulers'})}>{busy?'Revealing…':'Roll the d20 · reveal rulers'}</button></div><p>Each ruler carries an eight-player historical army. One d20 roll chooses the army you will command for this campaign.</p><div className="duat-army-grid">{faction?.armies.map(a=><article className="duat-army" key={a.id}><span className="duat-eyebrow">RULER {a.rulerNumber} · ROLL {a.rollBand.label}</span><h3>{a.season}</h3>{a.players.map(p=><div className="duat-army-player" key={p.id}><span>{p.position}</span><strong>{p.name}</strong></div>)}</article>)}</div>{room&&!room.canAdvance&&<p className="duat-notice">Every human faction must join and mark ready before the host reveals the rulers.</p>}</section>:<>
                    {flow?.stage==='complete'&&<section className="duat-crowned"><span className="duat-eyebrow">LORD OF THE DUAT</span><h2><Sigil id={campaign.championId}/>{factionName(campaign.championId)}</h2><p>{expanded?'Dynasty season '+campaign.dynastySeason+' enters the Royal Library. The walking rulers retire; the remaining tombs and your empire endure.':'Seventeen weeks. A dynasty written into history.'}</p>{expanded?<div className="duat-succession"><label className="duat-field">Year for the newly buried army<select aria-label="Next dynasty ruler year" value={nextYears.includes(nextYear)?nextYear:nextYears[0]||''} onChange={e=>setNextYear(Number(e.target.value))} disabled={busy||!host}>{nextYears.map(year=><option key={year} value={year}>{year} NFL season</option>)}</select></label><button className="duat-button primary" disabled={busy||recruitmentPending||waitingClaim||Boolean(room&&ready&&(!host||!room.canAdvance))||(!room||ready)&&!nextYears.length} onClick={()=>run(room&&!ready?{type:'set-ready',ready:true}:{type:'next-season',season:nextYears.includes(nextYear)?nextYear:nextYears[0]})}>{room&&!ready?'Mark ready for the next dynasty':room&&!host?'Waiting for the host':room&&!room.canAdvance?'Waiting for the other factions':'Continue dynasty · Season '+(campaign.dynastySeason+1)}</button>{room&&ready&&<button className="duat-link" disabled={busy} onClick={()=>run({type:'set-ready',ready:false})}>Unready my faction</button>}{rules.favors&&campaign.championId===me&&<button className="duat-button" disabled={busy} onClick={()=>setTab('rituals')}>Optional · visit the Throne Room</button>}{recruitmentPending&&<button className="duat-button" onClick={()=>setTab('rituals')}>Resolve the waiting Mahdi recruit</button>}<button className="duat-button" onClick={()=>setTab('library')}>Read the annals</button>{ownClaim&&<button className="duat-button" onClick={()=>moveFlow({type:'conquest-reopen',week:17})}>Resolve final conquest</button>}{waitingClaim&&<p className="duat-notice">Final conquest is still open. Resolve the earned claims and wars before continuing the dynasty.</p>}{room&&!room.canAdvance&&<p className="duat-muted">Every human faction must mark ready before the host continues.</p>}</div>:<button className="duat-button" onClick={home}>Start another campaign</button>}</section>}
                    {canExplore&&<details className="duat-weekly-explore"><summary>Explore the realm · optional views</summary><nav className="duat-tabs" aria-label="Campaign views">{[["home","Return to this week"],...(rules.conquest?[['world','Conquest']]:[]),...(expanded&&rules.favors?[['rituals','Favors of the Gods']]:[]),['gameday','Game day'],['tournaments','Heptad & playoffs'],['standings','All-play'],...(expanded?[['library','Royal Library']]:[]),...(room?[['friends','Friends']]:[])].map(([id,label])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}{id==='world'&&warReserve>0?' · '+warReserve:''}</button>)}</nav></details>}
                    {exploring&&<button className="duat-button duat-back-to-week" onClick={()=>setTab('home')}>← Return to Week {flow.week}</button>}
                    {!exploring&&flow&&flow.stage!=='complete'&&<Flow.Frame stage={flow.stage} week={flow.week} cycle={Progress.cycleOf(campaign)} primary={primary} secondary={secondary} note={flowNote} busy={busy} pendingRecruit={recruitmentPending} favors={rules.favors&&Boolean(flow.resultWeek?App.DuatFavors.SACRED_WEEKS.includes(flow.resultWeek)||flow.resultWeek===1:preparation?.hasUsableOptions)} conquest={rules.conquest}>
                        {flow.stage==='alliance'&&<App.DuatHeptadUI.AllianceIntro campaign={campaign} factionId={me}/>}
                        {flow.stage==='lineup'&&<Flow.Preparation campaign={campaign} factionId={me} lineup={lineup} onChange={setLineup} disabled={busy||ready} previous={last}/>}
                        {flow.stage==='favors'&&(expanded?<App.DuatRitualsView campaign={campaign} factionId={me} onAction={run} busy={busy} ready={ready} dirty={dirty} lineup={lineup} availablePlayers={recruitPool} poolLoaded={recruitPoolLoaded} actionError={error} notice={notice} guided eligibleIds={preparation.eligibleIds} eligibleTargets={preparation.eligibleTargets}/>:<Presentation.Pantheon actionError={error} notice={notice} campaign={campaign} faction={faction} army={army} favorId={favorId} setFavorId={setFavorId} target={target} setTarget={setTarget} sourceWeek={sourceWeek} setSourceWeek={setSourceWeek} run={run} busy={busy} ready={ready} dirty={dirty}/>)}
                        {flow.stage==='kickoff'&&<Flow.Kickoff campaign={campaign} factionId={me} room={room} ready={ready} preparation={preparation}/>}
                        {flow.stage==='games'&&<div className="duat-guided-game"><GameDay key={flowKey+':'+flow.resultWeek} campaign={campaign} factionId={me} resultWeek={flow.resultWeek} initialClock={flow.clock} onProgress={progressClock} guided/></div>}
                        {flow.stage==='recap'&&<Flow.Recap campaign={campaign} factionId={me} week={flow.resultWeek} result={currentResult}/>}
                        {flow.stage==='conquest'&&<><Flow.ConquestNote resultWeek={flow.resultWeek} ownClaim={ownClaim} waitingClaim={waitingClaim} enabled={rules.conquest} catchingUp={!flow.caughtUp}/>{rules.conquest&&flow.caughtUp&&<World campaign={campaign} factionId={me} busy={busy||ready||!expanded&&campaign.phase==='complete'} onAction={run} guided resultWeek={flow.resultWeek}/>}</>}
                    </Flow.Frame>}
                    {exploring&&tab==='gameday'&&<GameDay campaign={campaign} factionId={me}/>}
                    {rules.conquest&&exploring&&tab==='world'&&<World campaign={campaign} factionId={me} busy={busy||ready||!expanded&&campaign.phase==='complete'} onAction={run}/>}
                    {exploring&&tab==='standings'&&<section className="duat-panel"><h2>All-play standings</h2><p>Your score faces all {campaign.factions.length-1} rivals every week through Week {Engine.regularSeasonWeeks(campaign)}. Ties split a win; points break equal records.</p><div className="duat-table-wrap"><table><thead><tr><th>Rank</th><th>Faction</th><th>Wins</th><th>Losses</th><th>Points</th>{rules.conquest&&<th>Territory</th>}</tr></thead><tbody>{standings.map(s=><tr key={s.factionId} className={s.factionId===me?'is-mine':''}><td>{s.rank}</td><td><Sigil id={s.factionId}/>{s.name}{s.rank<=rules.playoffTeams&&campaign.week>Engine.regularSeasonWeeks(campaign)?' · Playoffs':''}</td><td>{s.wins}</td><td>{s.losses}</td><td>{n(s.points)}</td>{rules.conquest&&<td>{Object.values(campaign.conquest.owners).filter(id=>id===s.factionId).length}</td>}</tr>)}</tbody></table></div></section>}
                    {exploring&&tab==='tournaments'&&(expanded?<><App.DuatHeptadUI.Games campaign={campaign} factionId={me} onAction={run} busy={busy||ready}/><Tournaments campaign={campaign} factionId={me} onlyHeavenly/></>:<Tournaments campaign={campaign} factionId={me}/>)}
                    {expanded&&exploring&&tab==='rituals'&&rules.favors&&<><p className="duat-muted">{flow.resultWeek?'Finish the weekly report and war council before preparing another offering.':'You can return to the guided week whenever you are ready.'}</p><App.DuatRitualsView campaign={campaign} factionId={me} onAction={run} busy={busy||Boolean(flow.resultWeek)} ready={ready} dirty={dirty} lineup={lineup} availablePlayers={recruitPool} poolLoaded={recruitPoolLoaded} actionError={error} notice={notice}/></>}
                    {expanded&&exploring&&tab==='library'&&<App.DuatLibrary campaign={campaign} factionId={me} onAction={run} busy={busy||ready} deities={App.DuatRituals.DEITIES}/>}
                </>}
                {expanded&&['draft','reveal'].includes(campaign.phase)&&<details className="duat-panel duat-preseason-library"><summary>Royal Library · Name your rulers and explore the dynasty</summary><App.DuatLibrary campaign={campaign} factionId={me} onAction={run} busy={busy||ready} deities={App.DuatRituals.DEITIES}/></details>}
                {room&&(!flowActive||exploring)&&tab==='friends'&&<section className="duat-panel"><h2>Friends & invites</h2><p>Each friend claims one faction with their own Dynasty HQ email account.</p><div className="duat-friend-grid">{room.seats.map(seat=><div className="duat-friend" key={seat.factionId}><Sigil id={seat.factionId}/><div><strong>{factionName(seat.factionId)}</strong><span>{seat.controller==='ai'?'AI manager':seat.joined?seat.ready?'Ready':'Joined · preparing':'Awaiting friend'}</span></div>{seat.inviteCode&&<button className="duat-button" onClick={async()=>{const url=new URL(location.href);url.searchParams.set('duat','1');url.searchParams.set('duat_invite',seat.inviteCode);try{await navigator.clipboard.writeText(url.href);setNotice('Invitation link copied for '+factionName(seat.factionId)+'.');}catch{setNotice('Invitation code: '+seat.inviteCode);}}}>Copy invite</button>}</div>)}</div></section>}
                <footer className="duat-campaign-footer"><button className="duat-link" onClick={home}>Campaign shelf</button>{!room&&<button className="duat-button" onClick={()=>exportSave(campaign)}>Export campaign backup</button>}<span>{room?'Shared campaign · saved after every move':'Saved on this browser · export a backup to move devices'}</span></footer>
            </>}
            <footer className="duat-source">Historical statistics: <a href="https://github.com/nflverse/nflverse-data" target="_blank" rel="noreferrer">nflverse</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> · 2002–2025 · NFL regular-season weeks 1–17. Missing player records begin at zero; declared favors may adjust the final score.</footer>
            </main></div>;
    }
    window.DuatGame=DuatGame;
})();
