/* global React */
(function(){
    'use strict';
    const {useState,useEffect,useRef,useMemo}=React;
    const App=window.App, Engine=App.DuatCampaign, Rules=App.DuatRules, Store=App.DuatStorage;
    const base=(window.location.pathname.includes('/dist-preview/')?'../':'');
    const asset=path=>base+path;
    const n=value=>Number(value||0).toFixed(1);
    const factionName=id=>Rules.FACTIONS.find(f=>f.id===id)?.name||id;
    let dataPromise;
    async function loadData(){
        if(!dataPromise)dataPromise=Promise.all(['player-cards.json','nflverse-game-logs.csv','manifest.json'].map(async file=>{
            const response=await fetch(asset('data/duat/'+file));
            if(!response.ok)throw new Error('The historical archive could not load. Check your connection and try again.');
            return file.endsWith('.csv')?response.text():response.json();
        })).then(([cards,csv,manifest])=>({cards:App.TimeLeaguePlayerCards.buildPlayerCardIndex(cards),logIndex:App.TimeLeagueSeason.buildGameLogIndex(App.TimeLeagueSeason.parseGameLogCsv(csv).logs),manifest})).catch(error=>{dataPromise=null;throw error;});
        return dataPromise;
    }
    function exportSave(campaign){
        const blob=new Blob([JSON.stringify(campaign,null,2)],{type:'application/json'}), url=URL.createObjectURL(blob);
        const a=document.createElement('a');a.href=url;a.download='duat-'+campaign.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
    }
    function Sigil({id}){const f=Rules.FACTIONS.find(row=>row.id===id);return <span className="duat-sigil" style={{color:f?.color}} aria-hidden="true">{f?.sigil||'◈'}</span>;}
    function World({campaign,factionId,onClaim,busy}){
        const [selected,setSelected]=useState('');
        const frontier=App.DuatConquest.eligibleTerritories(campaign.conquest,factionId), pending=campaign.conquest.pendingClaims[factionId]||0;
        const points=Object.fromEntries(Rules.TERRITORIES.map(t=>[t.id,{x:(t.longitude+180)/360*1000,y:(90-t.latitude)/180*500}]));
        const territory=Rules.TERRITORIES.find(t=>t.id===selected);
        return <section className="duat-panel duat-world"><div className="duat-panel-heading"><div><span className="duat-eyebrow">THE KNOWN WORLD</span><h2>Your next conquest</h2></div><span className="duat-pill">{pending} claim{pending===1?'':'s'} available</span></div>
            <svg viewBox="0 0 1000 500" role="img" aria-label="Original Duat territories and connected routes" className="duat-map">
                <image href={asset('data/duat/land.svg')} width="1000" height="500"/>
                {Rules.ROUTES.map((r,i)=>{const a=points[r.from],b=points[r.to];return a&&b&&Math.abs(a.x-b.x)<500?<line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#537773" strokeOpacity=".4" strokeWidth="1" strokeDasharray={r.type==='land'?undefined:'3 4'}/>:null;})}
                {Rules.TERRITORIES.map(t=>{const p=points[t.id],owner=campaign.conquest.owners[t.id],f=Rules.FACTIONS.find(f=>f.id===owner);return <g key={t.id}><circle cx={p.x} cy={p.y} r={frontier.includes(t.id)&&pending>0?8:5} fill={f?.color||'#46645f'} stroke={t.id===selected?'#fff':owner===factionId?'#f2d59a':frontier.includes(t.id)&&pending>0?'#68ddbd':'#12231f'} strokeWidth={t.id===selected?3:1.5} onClick={()=>setSelected(t.id)} className="duat-map-node"><title>{t.name}: {owner?factionName(owner):'Unclaimed'}</title></circle></g>;})}
            </svg>
            <div className="duat-map-key"><span><i style={{background:Rules.FACTIONS.find(f=>f.id===factionId)?.color}}/> Your faction</span><span><i style={{background:'#68ddbd'}}/> Reachable frontier</span><span>Natural Earth geography</span></div>
            {territory&&<p>{territory.name} · {campaign.conquest.owners[territory.id]?factionName(campaign.conquest.owners[territory.id]):'Unclaimed'}{frontier.includes(territory.id)&&pending>0&&<button className="duat-button" disabled={busy} onClick={()=>onClaim(territory.id)}>Claim {territory.name}</button>}</p>}
            {pending>0&&frontier.length>0?<div className="duat-frontier" aria-label="Available territory claims">{frontier.map(id=><button key={id} className="duat-button" disabled={busy} onClick={()=>onClaim(id)}>Claim {Rules.TERRITORIES.find(t=>t.id===id)?.name}</button>)}</div>:<p className="duat-muted">{pending>0?'No connected frontier remains. You can continue the campaign.':'Win the week for two claims. Finish in the top half for one. Your homeland is protected.'}</p>}
        </section>;
    }
    function GameDay({campaign,factionId}){
        const weeks=campaign.completedWeeks;
        const [week,setWeek]=useState(weeks.at(-1)?.week||1), [clock,setClock]=useState(0),[playing,setPlaying]=useState(false),[duration,setDuration]=useState(60);
        useEffect(()=>{setWeek(weeks.at(-1)?.week||1);setClock(0);setPlaying(Boolean(weeks.length));},[weeks.length]);
        const snapshot=weeks.find(w=>w.week===week);
        const timeline=useMemo(()=>snapshot?App.TimeLeagueGamecast.buildGamecast({seed:campaign.id,week,scoring:Engine.SCORING,results:snapshot.factions.map(f=>({teamId:f.factionId,total:f.total,starters:f.players.filter(p=>p.starter).map(p=>({entryId:p.id,name:p.name,points:p.effectivePoints,stats:p.stats||App.TimeLeagueSeason.emptyStatLine(),factor:1}))}))}):null,[campaign.id,snapshot,week]);
        useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setClock(value=>Math.min(60,value+60/duration/5)),200);return()=>clearInterval(timer);},[playing,duration]);
        useEffect(()=>{if(clock>=60)setPlaying(false);},[clock]);
        if(!snapshot)return <section className="duat-panel"><h2>Game day awaits</h2><p>Set your starting five, then play Week 1 to watch the historical results unfold.</p></section>;
        const seen=timeline.events.filter(e=>e.t<=clock), totals={};seen.forEach(e=>{totals[e.teamId]=(totals[e.teamId]||0)+e.points;});
        const leaders=[...snapshot.factions].sort((a,b)=>(totals[b.factionId]||0)-(totals[a.factionId]||0));
        const my=snapshot.factions.find(f=>f.factionId===factionId);
        const feed=seen.filter(e=>e.teamId===factionId).slice(-8).reverse();
        return <div className="duat-two-column"><section className="duat-panel"><div className="duat-panel-heading"><div><span className="duat-eyebrow">HISTORICAL REPLAY</span><h2>{App.TimeLeagueGamecast.clockLabel(clock)}</h2></div><label>Week <select aria-label="Replay week" value={week} onChange={e=>{setWeek(Number(e.target.value));setClock(0);setPlaying(false);}}>{weeks.map(w=><option key={w.week} value={w.week}>{w.week}</option>)}</select></label></div>
            <div className="duat-score-hero"><Sigil id={factionId}/><div><span>{factionName(factionId)} · {my.season} army</span><strong>{n(totals[factionId])}</strong><span>fantasy points</span></div></div>
            <div className="duat-replay-track"><div style={{width:clock/60*100+'%'}}/></div>
            <div className="duat-actions"><button className="duat-button primary" onClick={()=>{if(clock>=60)setClock(0);setPlaying(!playing);}}>{clock>=60?'Replay':playing?'Pause':'Play'}</button><button className="duat-button" onClick={()=>{setPlaying(false);setClock(Math.min(60,Math.floor(clock/15+1)*15));}}>Next quarter</button><button className="duat-button" onClick={()=>{setClock(60);setPlaying(false);}}>Final</button><select aria-label="Replay duration" value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={60}>1 minute</option><option value={180}>3 minutes</option><option value={300}>5 minutes</option></select></div>
            <p className="duat-muted">Real weekly statistics. Quarter timing is illustrative. Results are already saved.</p>
            <div className="duat-feed" aria-live="off">{feed.length?feed.map((e,i)=><div key={i}><span>{e.description}</span><strong>{e.points>=0?'+':''}{n(e.points)}</strong></div>):<p>Kickoff · your army is taking the field.</p>}</div>
            {clock>=60&&my.favor&&<p className="duat-notice">{my.favor.status==='applied'?my.favor.name+' applied · '+my.favor.cost+' favor spent':my.favor.reason+' No favor spent.'}</p>}
        </section><section className="duat-panel"><h2>Around the realm</h2><div className="duat-score-list">{leaders.map((f,i)=><div key={f.factionId} className={f.factionId===factionId?'is-mine':''}><span>{i+1}</span><Sigil id={f.factionId}/><span>{factionName(f.factionId)}</span><strong>{n(totals[f.factionId])}</strong></div>)}</div></section></div>;
    }
    function Tournaments({campaign}){
        const allianceName=id=>campaign.alliances.find(a=>a.id===id)?.name||id;
        return <div className="duat-two-column"><section className="duat-panel"><span className="duat-eyebrow">ALLIES IN THE ARENA</span><h2>The Heptad Games</h2><p>Seven paired alliances. Best ball from the starting lineups, without favors.</p>{campaign.heptad?.championId&&<p className="duat-winner">Champions · {allianceName(campaign.heptad.championId)}</p>}
            {campaign.alliances.map(a=><div className="duat-alliance" key={a.id}><span className="duat-pill">{a.entry}</span><span>{a.name}</span><span>{campaign.heptad?.eliminatedIds.includes(a.id)?'Eliminated':campaign.heptad?.championId===a.id?'Champion':'In the games'}</span></div>)}
            {(campaign.heptad?.matches||[]).map((m,i)=><p className="duat-match" key={i}>W{m.week} · {allianceName(m.homeId)} <strong>{n(m.homeScore)}–{n(m.awayScore)}</strong> {allianceName(m.awayId)}</p>)}
            {campaign.heptad?.next&&<p className="duat-notice">Next: Week {campaign.heptad.next.week} · {allianceName(campaign.heptad.next.homeId)} vs {allianceName(campaign.heptad.next.awayId)}</p>}
        </section><section className="duat-panel"><span className="duat-eyebrow">THE ROAD TO THE THRONE</span><h2>Heavenly Battle</h2><p>The top seven after Week 14. First seed earns a bye; the survivors are reseeded.</p>
            {!campaign.playoffField.length?<p className="duat-notice">The field will be set after Week 14.</p>:campaign.playoffField.map((id,i)=><div className="duat-alliance" key={id}><span className="duat-pill">{i+1}</span><Sigil id={id}/><span>{factionName(id)}</span></div>)}
            {(campaign.heavenly?.matches||[]).map((m,i)=><p className="duat-match" key={i}>W{m.week} · {Rules.HEAVENLY_ROUND_LABELS[m.round]}<br/>{factionName(m.homeId)} <strong>{n(m.homeScore)}–{n(m.awayScore)}</strong> {factionName(m.awayId)}</p>)}
            {campaign.heavenly?.championId&&<p className="duat-winner">Lord of the Duat · {factionName(campaign.heavenly.championId)}</p>}{campaign.heavenly?.thirdPlaceId&&<p>The Camel · {factionName(campaign.heavenly.thirdPlaceId)}</p>}
        </section></div>;
    }
    function DuatGame({onClose}){
        const [campaign,setCampaign]=useState(null),[room,setRoom]=useState(null),[data,setData]=useState(null),[shelf,setShelf]=useState([]),[rooms,setRooms]=useState([]);
        const [mode,setMode]=useState(()=>{try{return new URLSearchParams(location.search).has('duat_invite')||sessionStorage.getItem('duat-pending-invite')?'friends':'solo';}catch{return 'solo';}}),[name,setName]=useState('The First Dynasty'),[factionId,setFactionId]=useState('egypt'),[endYear,setEndYear]=useState(2025),[humans,setHumans]=useState(2);
        const [tab,setTab]=useState('home'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[archiveLoading,setArchiveLoading]=useState(true);
        const [lineup,setLineup]=useState([]),[favorId,setFavorId]=useState('kratos-1'),[target,setTarget]=useState(''),[sourceWeek,setSourceWeek]=useState(1),[removeId,setRemoveId]=useState(null);
        const [invite,setInvite]=useState(()=>{const code=new URLSearchParams(window.location.search).get('duat_invite');try{if(code)sessionStorage.setItem('duat-pending-invite',code);return code||sessionStorage.getItem('duat-pending-invite')||'';}catch{return code||'';}});
        const activeRef=useRef(null),requestRef=useRef(0),fileRef=useRef(null),campaignRef=useRef(null);campaignRef.current=campaign;
        const accountId=App.OD?.getCurrentUserId?.();
        const accountRef=useRef(accountId);
        useEffect(()=>{if(accountRef.current!==accountId){accountRef.current=accountId;requestRef.current++;setRooms([]);setBusy(false);if(activeRef.current){activeRef.current=null;setRoom(null);setCampaign(null);setError('Your account changed. Open a campaign from your own account.');}}},[accountId]);
        const me=room?.self.factionId||campaign?.hostFactionId||factionId;
        const faction=campaign?.factions.find(f=>f.id===me),army=faction&&Engine.activeArmy(faction);
        const ready=Boolean(room?.seats.find(s=>s.factionId===me)?.ready),host=!room||room.self.role==='host';
        const seasons=data?Engine.availableSeasons(data):[];
        const epochs=seasons.filter(year=>[0,1,2,3].every(offset=>seasons.includes(year-offset)));
        const refreshShelf=()=>{try{setShelf(Store.list());}catch(e){setError(e.message);}};
        useEffect(()=>{let alive=true;refreshShelf();loadData().then(value=>{if(alive){setData(value);setEndYear(Engine.availableSeasons(value)[0]);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setArchiveLoading(false);});return()=>{alive=false;};},[]);
        useEffect(()=>{if(!faction)return;setLineup([...faction.lineup]);setTarget(faction.lineup[0]||'');},[campaign?.id,campaign?.week,JSON.stringify(faction?.lineup)]);
        const acceptRoom=(next,opening=false)=>{if(!next)return;const previous=activeRef.current;if(!opening&&(!previous||previous.id!==next.id))return;if(previous&&previous.id===next.id&&next.revision<previous.revision)return;activeRef.current=next;setRoom(next);setCampaign(next.campaign);};
        async function listRooms(){if(!accountId){setRooms([]);return;}const user=accountId,generation=requestRef.current;const result=await App.DuatRemote.request({op:'list'});if(user!==App.OD?.getCurrentUserId?.()||generation!==requestRef.current)return;if(result.ok)setRooms(result.rooms||[]);else setError(result.error);}
        useEffect(()=>{if(mode==='friends')listRooms();},[mode,accountId]);
        useEffect(()=>{
            if(!room?.id)return;
            const roomId=room.id, userId=accountId;let alive=true,inflight=false;
            async function refresh(){if(!alive||inflight)return;if(App.OD?.getCurrentUserId?.()!==userId){activeRef.current=null;setRoom(null);setCampaign(null);setError('Your account changed. Reopen your campaign.');return;}inflight=true;
                const result=await App.DuatRemote.request({op:'load',roomId});inflight=false;if(!alive||activeRef.current?.id!==roomId)return;
                if(result.ok)acceptRoom(result.room);else setError(result.error);
            }
            const timer=setInterval(refresh,4000);window.addEventListener('focus',refresh);window.addEventListener('online',refresh);
            return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh);};
        },[room?.id,accountId]);
        async function run(action){
            if(busy||!campaign)return;const generation=requestRef.current,user=accountId,originRoom=room?.id;const valid=()=>generation===requestRef.current&&(!originRoom||activeRef.current?.id===originRoom&&App.OD?.getCurrentUserId?.()===user);setBusy(true);setError('');setNotice('');
            try{
                if(room){const current=activeRef.current;const result=await App.DuatRemote.request({op:'action',roomId:current.id,expectedRevision:current.revision,actionId:crypto.randomUUID(),action:{...action,factionId:me}});
                    if(!valid())return;
                    if(!result.ok){if(result.conflict){const fresh=await App.DuatRemote.request({op:'load',roomId:current.id});if(!valid())return;if(fresh.ok)acceptRoom(fresh.room);}throw new Error(result.error);}
                    acceptRoom(result.room);
                }else{const next=Engine.applyAction(campaignRef.current,{...action,factionId:me,createdAt:new Date().toISOString()},data);Store.write(next);setCampaign(next);refreshShelf();}
                if(action.type==='advance-week')setTab('gameday');else if(action.type==='reveal-rulers')setNotice('Your ruler has returned. Set the starting five for Week 1.');else if(action.type==='set-lineup')setNotice('Starting five saved.');else if(action.type==='declare-favor')setNotice('Favor declared for this week.');else if(action.type==='claim')setNotice('Territory claimed.');
            }catch(e){if(valid())setError(e.message);}finally{if(valid())setBusy(false);}
        }
        async function create(event){event.preventDefault();if(busy)return;const generation=++requestRef.current,user=accountId;const valid=()=>generation===requestRef.current&&(mode!=='friends'||user===App.OD?.getCurrentUserId?.());setBusy(true);setError('');
            try{const chosen=[0,1,2,3].map(i=>endYear-i), humanFactionIds=mode==='friends'?[factionId,...Rules.FACTIONS.filter(f=>f.id!==factionId).slice(0,humans-1).map(f=>f.id)]:[factionId];
                if(mode==='friends'){const result=await App.DuatRemote.request({op:'create',input:{name,seasons:chosen,hostFactionId:factionId,humanFactionIds}});if(!valid())return;if(!result.ok)throw new Error(result.error);acceptRoom(result.room,true);}
                else{const next=Engine.createCampaign({id:crypto.randomUUID(),name,seasons:chosen,hostFactionId:factionId,humanFactionIds,seed:crypto.randomUUID(),createdAt:new Date().toISOString()},data);Store.write(next);activeRef.current=null;setRoom(null);setCampaign(next);refreshShelf();}
                setTab('home');
            }catch(e){if(valid())setError(e.message);}finally{if(valid())setBusy(false);}
        }
        async function openOnline(id){setBusy(true);setError('');const request=++requestRef.current,user=accountId;const result=await App.DuatRemote.request({op:'load',roomId:id});if(request!==requestRef.current||user!==App.OD?.getCurrentUserId?.())return false;if(result.ok){activeRef.current=null;acceptRoom(result.room,true);setTab('home');}else setError(result.error);setBusy(false);return Boolean(result.ok);}
        async function join(){const generation=++requestRef.current,user=accountId;setBusy(true);setError('');const result=await App.DuatRemote.request({op:'claim',code:invite.trim()});if(generation!==requestRef.current||user!==App.OD?.getCurrentUserId?.())return;if(result.ok){const opened=await openOnline(result.roomId||result.room?.id);if(!opened)return;try{sessionStorage.removeItem('duat-pending-invite');}catch{}setInvite('');const url=new URL(location.href);url.searchParams.delete('duat_invite');history.replaceState({},'',url);}else{setError(result.error);setBusy(false);}}
        function home(){requestRef.current++;activeRef.current=null;setCampaign(null);setRoom(null);setBusy(false);setError('');setNotice('');refreshShelf();if(mode==='friends')listRooms();}
        async function restore(file){if(!file)return;const generation=++requestRef.current;setError('');try{if(file.size>5000000)throw new Error('This backup is too large. Choose a Duat campaign backup under 5 MB.');const saved=JSON.parse(await file.text());if(generation!==requestRef.current)return;if(!Engine.validateCampaign(saved))throw new Error('Choose a valid Duat campaign backup.');Store.write(saved);setRoom(null);activeRef.current=null;setCampaign(saved);refreshShelf();setNotice('Campaign restored on this browser.');}catch(e){if(generation===requestRef.current)setError(e.message);}finally{if(fileRef.current)fileRef.current.value='';}}
        const pending=campaign?campaign.conquest.pendingClaims[me]||0:0;
        const reachable=campaign?App.DuatConquest.eligibleTerritories(campaign.conquest,me):[];
        const waitingClaim=campaign?.humanFactionIds.some(id=>campaign.conquest.pendingClaims[id]>0&&App.DuatConquest.eligibleTerritories(campaign.conquest,id).length>0);
        const legal=Boolean(faction&&Engine.legalLineup(faction,lineup));
        const dirty=Boolean(faction&&JSON.stringify([...lineup].sort())!==JSON.stringify([...faction.lineup].sort()));
        const standings=campaign?Engine.computeStandings(campaign):[];
        const last=campaign?.completedWeeks.at(-1),myLast=last?.factions.find(f=>f.factionId===me);
        const signedIn=Boolean(accountId&&App.OD?.getSessionToken?.());
        return <div className="duat-game"><header className="duat-topbar"><button className="duat-back" onClick={campaign?home:onClose}>← {campaign?'Campaigns':'Dynasty HQ'}</button><span className="duat-wordmark">THE DUAT <small>HISTORICAL</small></span><span className="duat-status">{room?'With friends':campaign?'Solo campaign':'Dynasty HQ Games'}</span></header>
            <main className="duat-main">{error&&<div role="alert" className="duat-alert">{error}<button className="duat-link" onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<p role="status" className="duat-notice">{notice}</p>}
            {!campaign?<><div className="duat-intro"><span className="duat-eyebrow">FOUR RULERS. ONE RETURN.</span><h1>Build a dynasty.<br/><em>Conquer the afterlife.</em></h1><p>Lead one of fourteen factions through a historical football season. Your starting five win the points. Your choices win the realm.</p></div>
                <div className="duat-setup-grid"><form className="duat-panel" onSubmit={create}><div className="duat-choice-row"><button type="button" className={'duat-choice '+(mode==='solo'?'selected':'')} aria-pressed={mode==='solo'} onClick={()=>setMode('solo')}><strong>Play Solo</strong><span>You and thirteen AI factions</span></button><button type="button" className={'duat-choice '+(mode==='friends'?'selected':'')} aria-pressed={mode==='friends'} onClick={()=>setMode('friends')}><strong>Play with Friends</strong><span>Private invites. Advance together.</span></button></div>
                    {mode==='friends'&&!signedIn&&<p className="duat-notice">Sign in with your Dynasty HQ email account to create or join a campaign. <a href={asset('login.html?duat=1')}>Sign in</a></p>}
                    <label className="duat-field">Campaign name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>
                    <div className="duat-form-row"><label className="duat-field">Four ruler years<select aria-label="Four ruler years" value={endYear} onChange={e=>setEndYear(Number(e.target.value))}>{epochs.map(year=><option key={year} value={year}>{year-3}–{year}</option>)}</select></label>{mode==='friends'&&<label className="duat-field">Human factions<select value={humans} onChange={e=>setHumans(Number(e.target.value))}>{Array.from({length:13},(_,i)=>i+2).map(x=><option key={x} value={x}>{x} friends · {14-x} AI</option>)}</select></label>}</div>
                    <fieldset className="duat-faction-picker"><legend>Choose your faction</legend>{Rules.FACTIONS.map(f=><button key={f.id} type="button" className={'duat-faction-choice '+(factionId===f.id?'selected':'')} aria-pressed={factionId===f.id} onClick={()=>setFactionId(f.id)}><Sigil id={f.id}/><span>{f.name}</span></button>)}</fieldset>
                    <button className="duat-button primary duat-wide" disabled={busy||archiveLoading||!data||!name.trim()||(mode==='friends'&&!signedIn)}>{busy?'Founding your dynasty…':archiveLoading?'Loading the historical archive…':mode==='solo'?'Begin solo campaign':'Create friends’ campaign'}</button>
                    {!data&&!archiveLoading&&<button type="button" className="duat-button" onClick={()=>{setArchiveLoading(true);loadData().then(setData).catch(e=>setError(e.message)).finally(()=>setArchiveLoading(false));}}>Retry archive</button>}
                    <p className="duat-muted">One quarterback, four flex starters, three on the bench. Four buried armies. One $100 favor treasury. Weeks 1–17.</p>
                </form><aside className="duat-setup-aside"><div className="duat-faction-banner" style={{'--faction-color':Rules.FACTIONS.find(f=>f.id===factionId)?.color}}><Sigil id={factionId}/><span className="duat-eyebrow">YOUR FACTION</span><h2>{factionName(factionId)}</h2><p>{Rules.FACTIONS.find(f=>f.id===factionId)?.motto}</p><span>{Rules.FACTIONS.find(f=>f.id===factionId)?.realm}</span></div>
                    <section className="duat-panel"><h2>Return to a campaign</h2>{shelf.length?shelf.map(saved=><div className="duat-save-row" key={saved.id}><button className="duat-save-open" onClick={()=>{try{const state=Store.read(saved.id);requestRef.current++;setBusy(false);setCampaign(state);setRoom(null);activeRef.current=null;setTab('home');}catch(e){setError(e.message);}}}><strong>{saved.name}</strong><span>{factionName(saved.factionId)} · {saved.phase==='complete'?'Complete':saved.phase==='preseason'?'Rulers await':'Week '+saved.week}</span></button><button className="duat-link" onClick={()=>{if(removeId===saved.id){try{Store.remove(saved.id);refreshShelf();setRemoveId(null);}catch(e){setError(e.message);}}else setRemoveId(saved.id);}}>{removeId===saved.id?'Confirm delete':'Delete'}</button></div>):<p className="duat-muted">Your solo campaigns will be saved here on this browser.</p>}
                        <button className="duat-button" onClick={()=>fileRef.current.click()}>Restore a backup</button><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={e=>restore(e.target.files[0])}/>
                    </section>{mode==='friends'&&<section className="duat-panel"><h2>Your friends’ campaigns</h2>{rooms.map(saved=><button className="duat-save-open" key={saved.id} disabled={busy} onClick={()=>openOnline(saved.id)}><strong>{saved.name}</strong><span>{saved.phase==='preseason'?'Waiting room':'Week '+saved.week}</span></button>)}<label className="duat-field">Invitation code<input value={invite} onChange={e=>setInvite(e.target.value)} placeholder="Paste your invitation code"/></label><button className="duat-button" disabled={!invite.trim()||busy||!signedIn} onClick={join}>Join campaign</button></section>}
                </aside></div></>:<><section className="duat-campaign-heading"><div className="duat-campaign-identity"><Sigil id={me}/><div><span className="duat-eyebrow">{campaign.name}</span><h1>{factionName(me)}</h1><p>{army?`${army.season} ruler · d20 roll ${faction.rulerRoll}`:'The buried rulers await your return.'}</p></div></div><div className="duat-campaign-facts"><span><strong>{campaign.phase==='complete'?'Final':campaign.phase==='preseason'?'Ritual':'Week '+campaign.week}</strong>{campaign.week>=15&&campaign.phase==='season'?'Heavenly Battle':'Historical campaign'}</span><span><strong>${faction?.favorBalance??100}</strong>Favor treasury</span><span><strong>{Object.values(campaign.conquest.owners).filter(id=>id===me).length}</strong>Territories</span></div></section>
                {room&&<section className="duat-room-bar"><span>{room.seats.filter(s=>s.controller==='human'&&s.joined).length} of {room.seats.filter(s=>s.controller==='human').length} human factions joined</span><span>{room.seats.filter(s=>s.controller==='human'&&s.ready).length} ready</span>{campaign.phase!=='complete'&&<button className={'duat-button '+(!ready?'primary':'')} disabled={busy||!ready&&(dirty||pending>0&&reachable.length>0)} onClick={()=>run({type:'set-ready',ready:!ready})}>{ready?'Ready · change to unready':'Mark my faction ready'}</button>}<button className="duat-link" onClick={()=>setTab('friends')}>Friends & invites</button></section>}
                {campaign.phase==='preseason'?<section className="duat-panel"><div className="duat-panel-heading"><div><span className="duat-eyebrow">THE RESURRECTION</span><h2>Which ruler will walk again?</h2></div><button className="duat-button primary" disabled={busy||!data||!host||Boolean(room&&!room.canAdvance)} onClick={()=>run({type:'reveal-rulers'})}>{busy?'Revealing…':'Roll the d20 · reveal rulers'}</button></div><p>Each ruler carries an eight-player historical army. One d20 roll chooses the army you will command for this campaign.</p><div className="duat-army-grid">{faction?.armies.map(a=><article className="duat-army" key={a.id}><span className="duat-eyebrow">RULER {a.rulerNumber} · ROLL {a.rollBand.label}</span><h3>{a.season}</h3>{a.players.map(p=><div className="duat-army-player" key={p.id}><span>{p.position}</span><strong>{p.name}</strong></div>)}</article>)}</div>{room&&!room.canAdvance&&<p className="duat-notice">Every human faction must join and mark ready before the host reveals the rulers.</p>}</section>:<>
                    {campaign.phase==='complete'&&<section className="duat-crowned"><span className="duat-eyebrow">LORD OF THE DUAT</span><h2><Sigil id={campaign.championId}/>{factionName(campaign.championId)}</h2><p>Seventeen weeks. Fourteen factions. A dynasty written into history.</p><button className="duat-button" onClick={home}>Start another campaign</button></section>}
                    <nav className="duat-tabs" aria-label="Campaign views">{[['home','My faction'],['gameday','Game day'],['world','Conquest'],['standings','All-play'],['tournaments','Tournaments'],...(room?[['friends','Friends']]:[])].map(([id,label])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}{id==='world'&&pending>0?' · '+pending:''}</button>)}</nav>
                    {tab==='home'&&<div className="duat-two-column"><section className="duat-panel"><div className="duat-panel-heading"><div><span className="duat-eyebrow">{army?.season} ARMY</span><h2>Your starting five</h2></div><span className="duat-pill">{lineup.length}/5 selected</span></div><p className="duat-muted">One QB and four RB, WR or TE. Estimates use earlier seasons and completed campaign weeks.</p><div className="duat-roster">{army?.players.map(p=>{const estimate=Engine.estimatePlayer(campaign,me,p.id),previous=myLast?.players.find(item=>item.id===p.id);return <label key={p.id} className={'duat-player '+(lineup.includes(p.id)?'starting':'')}><input type="checkbox" disabled={busy||ready||campaign.phase==='complete'} checked={lineup.includes(p.id)} onChange={()=>setLineup(ids=>ids.includes(p.id)?ids.filter(id=>id!==p.id):[...ids,p.id])}/><span className="duat-position">{p.position}</span><span className="duat-player-name"><strong>{p.name}</strong><small>{estimate.label}</small></span><span className="duat-player-points"><strong>{n(estimate.points)}</strong><small>Est. PPG</small></span>{previous&&<span className="duat-player-points"><strong>{n(previous.effectivePoints)}</strong><small>W{last.week}</small></span>}</label>;})}</div><div className="duat-actions"><button className="duat-button primary" disabled={!dirty||!legal||busy||ready||campaign.phase==='complete'} onClick={()=>run({type:'set-lineup',playerIds:lineup})}>Save starting five</button><button className="duat-button" disabled={busy||ready||campaign.phase==='complete'} onClick={()=>setLineup(Engine.recommendedLineup(campaign,me))}>Suggest lineup</button></div>{!legal&&<p className="duat-error">Select exactly one quarterback and four other starters.</p>}{dirty&&<p className="duat-muted">Save your lineup before playing or marking ready.</p>}
                    </section><div className="duat-side-stack"><section className="duat-panel duat-next"><span className="duat-eyebrow">YOUR NEXT MOVE</span><h2>{pending>0&&reachable.length?'Claim your frontier':campaign.phase==='complete'?'Your campaign is complete':`Play Week ${campaign.week}`}</h2>{myLast&&<p>Last week: <strong>{n(myLast.total)} points</strong> · {n(myLast.baseTotal)} before favors.</p>}{pending>0&&reachable.length?<button className="duat-button primary" onClick={()=>setTab('world')}>Choose your conquest</button>:campaign.phase!=='complete'&&<button className="duat-button primary duat-wide" disabled={busy||!data||dirty||!host||Boolean(room&&!room.canAdvance)||waitingClaim} onClick={()=>run({type:'advance-week'})}>{busy?'Resolving historical games…':`Play Week ${campaign.week}`}</button>}{room&&!host&&<p className="duat-muted">The host advances after everyone is ready.</p>}{waitingClaim&&!(pending>0&&reachable.length>0)&&<p className="duat-muted">Another human faction still has territory to claim.</p>}</section>
                        <section className="duat-panel"><span className="duat-eyebrow">{Rules.SACRED_WEEKS.includes(campaign.week)?'SACRED WEEK':'THE PANTHEON'}</span><h2>Call in a favor</h2>{Rules.SACRED_WEEKS.includes(campaign.week)&&campaign.phase==='season'?<><label className="duat-field">Favor<select value={favorId} disabled={ready} onChange={e=>setFavorId(e.target.value)}>{App.DuatFavors.FAVORS.map(f=><option key={f.id} value={f.id}>{f.name} · ${f.cost}</option>)}</select></label><p>{App.DuatFavors.FAVORS.find(f=>f.id===favorId)?.effect}</p><label className="duat-field">Starter<select value={target} disabled={ready} onChange={e=>setTarget(e.target.value)}>{army?.players.filter(p=>faction.lineup.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{favorId.startsWith('janus')&&<label className="duat-field">Borrow from week<select value={favorId==='janus-2'?campaign.week-1:sourceWeek} onChange={e=>setSourceWeek(Number(e.target.value))} disabled={ready||favorId==='janus-2'}>{campaign.completedWeeks.map(w=><option key={w.week} value={w.week}>{w.week}</option>)}</select></label>}<div className="duat-actions"><button className="duat-button" disabled={busy||ready||dirty||!target} onClick={()=>run({type:'declare-favor',favorId,playerId:target,...(favorId.startsWith('janus')?{sourceWeek:favorId==='janus-2'?campaign.week-1:sourceWeek}:{})})}>Declare favor</button>{faction.declaredFavor&&<button className="duat-link" disabled={busy||ready} onClick={()=>run({type:'clear-favor'})}>Clear</button>}</div>{faction.declaredFavor&&<p className="duat-notice">Declared: {App.DuatFavors.FAVORS.find(f=>f.id===faction.declaredFavor.favorId)?.name} for {army?.players.find(p=>p.id===faction.declaredFavor.playerId)?.name}.</p>}</>:<p>Favors open in weeks 5, 7, 10, 14, 15, 16 and 17. Your treasury lasts the season.</p>}<p className="duat-muted">Seven scoring favors are available in this historical beta. Heptad scores are unaffected.</p></section></div></div>}
                    {tab==='gameday'&&<GameDay campaign={campaign} factionId={me}/>}
                    {tab==='world'&&<World campaign={campaign} factionId={me} busy={busy||ready} onClaim={id=>run({type:'claim',territoryId:id})}/>}
                    {tab==='standings'&&<section className="duat-panel"><h2>All-play standings</h2><p>Your score faces all thirteen rivals every week through Week 14. Ties split a win; points break equal records.</p><div className="duat-table-wrap"><table><thead><tr><th>Rank</th><th>Faction</th><th>Wins</th><th>Losses</th><th>Points</th><th>Territory</th></tr></thead><tbody>{standings.map(s=><tr key={s.factionId} className={s.factionId===me?'is-mine':''}><td>{s.rank}</td><td><Sigil id={s.factionId}/>{s.name}{s.rank<=7&&campaign.week>=15?' · Playoffs':''}</td><td>{s.wins}</td><td>{s.losses}</td><td>{n(s.points)}</td><td>{Object.values(campaign.conquest.owners).filter(id=>id===s.factionId).length}</td></tr>)}</tbody></table></div></section>}
                    {tab==='tournaments'&&<Tournaments campaign={campaign}/>}
                </>}
                {room&&tab==='friends'&&<section className="duat-panel"><h2>Friends & invites</h2><p>Each friend claims one faction with their own Dynasty HQ email account.</p><div className="duat-friend-grid">{room.seats.map(seat=><div className="duat-friend" key={seat.factionId}><Sigil id={seat.factionId}/><div><strong>{factionName(seat.factionId)}</strong><span>{seat.controller==='ai'?'AI manager':seat.joined?seat.ready?'Ready':'Joined · preparing':'Awaiting friend'}</span></div>{seat.inviteCode&&<button className="duat-button" onClick={async()=>{const url=new URL(location.href);url.searchParams.set('duat','1');url.searchParams.set('duat_invite',seat.inviteCode);try{await navigator.clipboard.writeText(url.href);setNotice('Invitation link copied for '+factionName(seat.factionId)+'.');}catch{setNotice('Invitation code: '+seat.inviteCode);}}}>Copy invite</button>}</div>)}</div></section>}
                <footer className="duat-campaign-footer"><button className="duat-link" onClick={home}>Campaign shelf</button>{!room&&<button className="duat-button" onClick={()=>exportSave(campaign)}>Export campaign backup</button>}<span>{room?'Shared campaign · saved after every move':'Saved on this browser · export a backup to move devices'}</span></footer>
            </>}
            <footer className="duat-source">Historical statistics: <a href="https://github.com/nflverse/nflverse-data" target="_blank" rel="noreferrer">nflverse</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> · 2002–2025 · NFL regular-season weeks 1–17. Missing player records score zero.</footer>
            </main></div>;
    }
    window.DuatGame=DuatGame;
})();
