function CupHonours({league}) {
 const empty=()=>({season:String(league.season||new Date().getFullYear()),cupName:'League Cup',winner:'',runnerUp:'',winnerScore:'',runnerScore:'',notes:''});
 const [records,setRecords]=React.useState([]),[manage,setManage]=React.useState(false),[form,setForm]=React.useState(empty),[editing,setEditing]=React.useState(false),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[loaded,setLoaded]=React.useState(false);
 const call=async body=>{const db=window.App?.OD?.getClient?.()||window.OD?.getClient?.();if(!db)throw Error('Sign in to view Cup history.');const {data,error:e}=await db.functions.invoke('league-cup',{body:{leagueId:String(league.league_id||league.id),season:String(league.season),...body}});if(e){let msg=e.message;try{msg=(await e.context.json()).error||msg;}catch{}throw Error(msg);}if(data.error)throw Error(data.error);return data;};
 const load=async()=>{setBusy(true);try{const data=await call({action:'history'});setRecords(data.records||[]);setManage(data.canManage);setLoaded(true);setError('');}catch(e){setError(e.message);}finally{setBusy(false);}};
 React.useEffect(()=>{load();},[]);
 const edit=r=>{setForm(r?{season:r.season,...r.result,cupName:r.result.cupName||'Woeppel Cup',winnerScore:r.result.winnerScore??'',runnerScore:r.result.runnerScore??''}:empty());setEditing(true);};
 const save=async e=>{e.preventDefault();setBusy(true);try{const previous=records.find(r=>r.season===form.season);const data=await call({action:'save-history',season:form.season,revision:previous?.revision||0,state:{cupName:form.cupName||'Woeppel Cup',winner:form.winner,runnerUp:form.runnerUp,winnerScore:form.winnerScore===''?null:Number(form.winnerScore),runnerScore:form.runnerScore===''?null:Number(form.runnerScore),notes:form.notes}});setRecords(prev=>[...prev.filter(r=>r.season!==form.season),data.record].sort((a,b)=>b.season.localeCompare(a.season)));setEditing(false);setError('');}catch(err){setError(err.message);}finally{setBusy(false);}};
 return <section className="cup-panel"><header className="cup-hero"><div><span className="cup-eyebrow">{league.name} · HALL OF FAME</span><h2>Cup <em>history</em></h2><p>The champions. The finals. The league’s Cup history.</p></div><div className="cup-hero-actions"><button disabled={busy} onClick={load}>Refresh</button>{manage&&<button disabled={busy} onClick={()=>edit(null)}>Record a winner</button>}</div></header>
 {error&&<p role="alert">{error}</p>}
 {editing&&manage&&<form onSubmit={save} className="cup-admin-tools"><fieldset disabled={busy} style={{border:0,minWidth:0,width:'100%',display:'grid',gap:12}}><legend>Record Cup result</legend><div className="cup-setup"><label>Season<input type="number" min="2000" max="2099" required value={form.season} onChange={e=>setForm({...form,season:e.target.value})}/></label>{[['cupName','Tournament name'],['winner','Winner'],['runnerUp','Runner-up (optional)']].map(([key,label])=><label key={key}>{label}<input required={key==='winner'||key==='cupName'} maxLength={key==='cupName'?80:120} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}{[['winnerScore','Winner score'],['runnerScore','Runner-up score']].map(([key,label])=><label key={key}>{label}<input type="number" step="0.01" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><label>Notes / source<input maxLength={1000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><p className="cup-note">Use the team or owner name as it appeared that season. Leave scores blank if unknown. Saving an existing season updates its record.</p><div><button type="submit">{busy?'Saving…':'Save result'}</button> <button type="button" onClick={()=>setEditing(false)}>Cancel</button></div></fieldset></form>}
 {!loaded&&!error&&<p>Loading the honours board…</p>}{loaded&&!records.length&&<div className="cup-awaiting"><h3>The first name belongs here.</h3><p>{manage?'Record previous Cup winners to build the archive.':'The commissioner has not recorded any Cup winners yet.'}</p></div>}
 <div className="cup-fixtures">{records.map(r=><article className="cup-match" key={r.season}><span className="cup-eyebrow">{r.season} · {r.result.cupName||'Woeppel Cup'} CHAMPION</span><h3>🏆 {r.result.winner}</h3>{r.result.runnerUp&&<p>Runner-up · {r.result.runnerUp}</p>}{r.result.winnerScore!==null&&<p>Final · <b>{r.result.winnerScore.toFixed(2)} – {r.result.runnerScore.toFixed(2)}</b></p>}{r.result.notes&&<p className="cup-note">{r.result.notes}</p>}{manage&&<button disabled={busy} onClick={()=>edit(r)}>Edit result</button>}</article>)}</div><p className="cup-note">Commissioner-recorded results, shared across this league’s connected Sleeper seasons.</p></section>;
}
window.CupHonours=CupHonours;
