/* global React */
(function () {
    'use strict';
    const { useState, useEffect, useMemo } = React;
    const App = window.App, Heptad = App.DuatHeptad;
    const num = value => Number(value || 0).toFixed(2);
    const labels = { top: 'Challenger path', bottom: 'Redemption path', championship: 'Championship', rematch: 'Championship reset', pinnacle: 'Pinnacle Battle' };
    const statusLabels = { waiting: 'Waiting to enter', unbeaten: 'Unbeaten', redemption: 'One life remains', eliminated: 'Journey complete', champion: 'Alliance champion' };
    function FactionMark({ faction }) {
        const Sigil = App.DuatPresentation?.Sigil;
        return Sigil ? <Sigil id={faction.id}/> : <span className="duat-sigil" style={{ color: faction.color }} aria-hidden="true">{faction.sigil || '◈'}</span>;
    }
    function RulesControls({ value, onChange, disabled = false }) {
        const options = Heptad.normalizeOptions(value);
        return <fieldset className="duat-heptad-rules" disabled={disabled}><legend>Alliance best-ball rules</legend><p className="duat-muted">Best ball is the 2024 original format. These choices make the player pool and scoring explicit.</p><div className="duat-form-row">
            <label className="duat-field">Eligible players<select value={options.pool} onChange={event => onChange({ ...options, pool: event.target.value })}><option value="starters">Both submitted starting lineups</option><option value="army">Both full armies, including benches</option></select></label>
            <label className="duat-field">Different years of the same athlete<select value={options.duplicates} onChange={event => onChange({ ...options, duplicates: event.target.value })}><option value="allow">Allow separate season cards</option><option value="unique-athlete">Count each athlete once</option></select></label>
            <label className="duat-field">Divine interventions<select value={options.favorPoints ? 'yes' : 'no'} onChange={event => onChange({ ...options, favorPoints: event.target.value === 'yes' })}><option value="no">Use base football scores</option><option value="yes">Include favor-adjusted scores</option></select></label>
        </div></fieldset>;
    }
    function Banner({ alliance, factionOf, large = false }) {
        return <div className={'duat-heptad-banner' + (large ? ' large' : '')}><div className="duat-heptad-standards">{alliance.teamIds.map(id => { const faction = factionOf(id); return <div className="duat-heptad-standard" style={{ '--standard-color': faction.color || '#d5b36d' }} key={id}><FactionMark faction={faction}/><span>{faction.name}</span></div>; })}</div><h3>{alliance.name}</h3><span className="duat-eyebrow">ENTRY {alliance.entry}</span></div>;
    }
    function Draw({ alliances, factionOf, myId }) {
        const ordered = [...alliances].sort((a,b)=>a.entry-b.entry);
        const [shown, setShown] = useState(0);
        useEffect(() => setShown(0), [alliances.map(a=>a.teamIds.join(':')).join('|')]);
        const current = ordered[shown - 1];
        return <section className="duat-heptad-draw duat-panel"><span className="duat-eyebrow">THE COUNCIL OF ALLIANCES</span><h2>Two banners. One fate.</h2><p>Partners and entrance order were drawn when this season was founded. Each victor holds the arena until the next alliance arrives.</p><div className="duat-heptad-reveal" aria-live="polite" aria-atomic="true">{current ? <><Banner alliance={current} factionOf={factionOf} large/><p>{current.id === myId ? `These are your allies. Your road through the ${Heptad.tournamentName(alliances)} begins here.` : `${current.name} will enter ${current.entry <= 2 ? 'in the opening battle' : `after ${current.entry - 2} challenger ${current.entry === 3 ? 'battle' : 'battles'}`}.`}</p></> : <div className="duat-heptad-sealed"><span aria-hidden="true">✦</span><h3>The standards are still furled.</h3><p>Unveil the first partnership.</p></div>}</div><div className="duat-actions"><button className="duat-button primary" disabled={shown >= ordered.length} onClick={()=>setShown(n=>n+1)}>{shown ? `Unveil next alliance · ${shown}/${ordered.length}` : 'Begin the alliance reveal'}</button>{shown < ordered.length && <button className="duat-button" onClick={()=>setShown(ordered.length)}>Show all alliances</button>}{shown === ordered.length && <button className="duat-button" onClick={()=>setShown(0)}>Replay the ceremony</button>}</div><ol className="duat-heptad-procession" aria-label="Revealed entrance order">{ordered.slice(0,shown).map(alliance=><li key={alliance.id} className={alliance.id===myId?'is-mine':''}><span>{alliance.entry}</span><strong>{alliance.name}</strong><small>{alliance.teamIds.map(id=>factionOf(id).name).join(' + ')}</small></li>)}</ol></section>;
    }
    function NameAlliance({ alliance, onAction, busy, locked = false }) {
        const [name, setName] = useState(alliance.name), [error, setError] = useState('');
        useEffect(()=>{setName(alliance.name);setError('');},[alliance.id,alliance.name]);
        const submit = event => { event.preventDefault(); if (locked) return; try { const next = Heptad.validateName(name); setError(''); onAction({ type: 'name-alliance', name: next }); } catch (cause) { setError(cause.message); } };
        return <form onSubmit={submit} className="duat-heptad-name"><label className="duat-field">Name your alliance<input value={name} disabled={locked || busy} maxLength={60} onChange={event=>setName(event.target.value)} placeholder="A name for two civilizations"/></label><button className="duat-button" disabled={locked || busy || name.trim() === alliance.name} type="submit">Raise this banner</button>{locked && <p className="duat-muted">This banner is recorded for the season. Alliance names lock after the first completed week.</p>}{error && <p className="duat-error" role="alert">{error}</p>}</form>;
    }
    function Match({ match, nameOf, myId, completedWeeks }) {
        const mvp = match.mvp || Heptad.matchMVP(match, completedWeeks);
        return <article className={'duat-heptad-match'+([match.homeId,match.awayId].includes(myId)?' is-mine':'')}><span className="duat-eyebrow">WEEK {match.week} · {labels[match.bracket]}</span>{[match.homeId,match.awayId].map((id,index)=><div className={match.winnerId===id?'winner':''} key={id}><span>{nameOf(id)}{match.winnerId===id && <small>Winner</small>}</span><strong>{num(index?match.awayScore:match.homeScore)}</strong></div>)}{mvp && <p className="duat-heptad-mvp"><span>Match MVP</span> {mvp.name} · {num(mvp.points)} points</p>}{match.tied && <p className="duat-muted">Tied scores: the reigning title holder keeps the Pinnacle.</p>}</article>;
    }
    function Pinnacle({ pinnacle, campaign, factionId, nameOf, factionOf, onAction, busy, completedWeeks }) {
        const minimum = Math.max(pinnacle.earliestWeek, campaign.week);
        const [week, setWeek] = useState(pinnacle.week || minimum);
        useEffect(()=>setWeek(pinnacle.week || minimum),[pinnacle.week,minimum]);
        const participating = pinnacle.participantFactionIds.includes(factionId), approved = pinnacle.approvedFactionIds.includes(factionId);
        const weeks = Array.from({length:Math.max(0,pinnacle.lastWeek-minimum+1)},(_,index)=>minimum+index);
        const closed = ['complete','declined','unavailable'].includes(pinnacle.status), expired = !weeks.length && !closed;
        return <section className="duat-panel duat-heptad-pinnacle"><span className="duat-eyebrow">AFTER THE CROWN · OPTIONAL TITLE DEFENSE</span><h2>The Pinnacle Battle</h2>{pinnacle.status==='unavailable' ? <p>No eligible challenger or unplayed week remains for a Pinnacle Battle this season.</p> : <><p><strong>{nameOf(pinnacle.championId)}</strong> can defend its title against <strong>{nameOf(pinnacle.challengerId)}</strong>, the leading alliance that missed the final.</p><p className="duat-muted">The challenger is chosen by tournament wins, then points, then alliance ID. Every participating faction must agree to the week. A tie keeps the title with the reigning champion. The original Heptad result stays in the Annals.</p>{pinnacle.status==='complete' && <><p className="duat-winner">{nameOf(pinnacle.result.winnerId)} · {pinnacle.result.defended?'Title defended':'Pinnacle victor'}</p><Match match={pinnacle.result} nameOf={nameOf} myId={null} completedWeeks={completedWeeks}/></>}{pinnacle.status==='declined' && <p className="duat-notice">The optional challenge was declined. The Heptad champions keep their tournament crown.</p>}{pinnacle.status==='scheduled' && <p className="duat-notice">All factions agreed. The title defense is set for Week {pinnacle.week}; it resolves with that week's football scores.</p>}{expired && <p className="duat-notice">No unplayed week remains. The Heptad championship stands.</p>}{!closed && !expired && pinnacle.status!=='scheduled' && <><p>{pinnacle.status==='proposed'?`Week ${pinnacle.week} has been proposed.`:'The champions may accept one final challenge.'}</p><div className="duat-heptad-consent">{pinnacle.participantFactionIds.map(id=><span key={id}><FactionMark faction={factionOf(id)}/>{factionOf(id).name}<strong>{pinnacle.approvedFactionIds.includes(id)?'Agreed':'Waiting'}</strong></span>)}</div>{participating && onAction && <div className="duat-actions"><label className="duat-field">Propose a week<select value={week} onChange={event=>setWeek(Number(event.target.value))}>{weeks.map(value=><option key={value} value={value}>Week {value}</option>)}</select></label><button className="duat-button" disabled={busy} onClick={()=>onAction({type:'propose-pinnacle',week})}>Propose Week {week}</button>{pinnacle.status==='proposed' && !approved && pinnacle.week>=campaign.week && <button className="duat-button primary" disabled={busy} onClick={()=>onAction({type:'approve-pinnacle'})}>Agree to Week {pinnacle.week}</button>}<button className="duat-button" disabled={busy} onClick={()=>onAction({type:'decline-pinnacle'})}>Decline challenge</button></div>}{!participating && <p className="duat-muted">The four participating factions decide whether to defend the title.</p>}</>}</>}</section>;
    }
    function Annals({ records, history, factionOf }) {
        const champions = Heptad.championGallery(history);
        return <div className="duat-heptad-annals"><section className="duat-panel"><span className="duat-eyebrow">THE NAMES THE ARENA REMEMBERS</span><h2>Champion gallery</h2>{champions.length ? <div className="duat-heptad-gallery">{champions.map((record,index)=><article key={record.seasonId+':'+record.allianceId}><span aria-hidden="true">✦</span><small>{record.seasonLabel || `Season ${index + 1}`}</small><h3>{record.name}</h3><p>{record.teamIds.map(id=>factionOf(id).name).join(' + ')}</p><strong>{record.wins} wins · {num(record.pointsFor)} points</strong>{record.pinnacleWins>0 && <small>Pinnacle victor</small>}</article>)}</div> : <p>The first champions will earn a permanent place here. These records come from your campaigns.</p>}</section><section className="duat-panel"><span className="duat-eyebrow">THIS SEASON'S ALLIANCES</span><h2>Every entrance leaves a record</h2><div className="duat-heptad-records">{records.map(record=><article key={record.allianceId}><div><h3>{record.name}</h3><span>Entry {record.entry}{record.champion?' · Champion':record.finalist?' · Finalist':''}</span></div><dl><div><dt>Record</dt><dd>{record.wins}–{record.losses}</dd></div><div><dt>Points for</dt><dd>{num(record.pointsFor)}</dd></div><div><dt>Against</dt><dd>{num(record.pointsAgainst)}</dd></div><div><dt>Redemption wins</dt><dd>{record.redemptionWins}</dd></div></dl>{record.bestWeek && <p>Finest battle · Week {record.bestWeek.week}, {num(record.bestWeek.points)} points</p>}</article>)}</div></section></div>;
    }
    function Games({ campaign, factionId, onAction, busy = false, options: passedOptions, history: passedHistory, pinnacle: passedPinnacle, seasonId: passedSeasonId, canManage = true }) {
        const options = Heptad.normalizeOptions(passedOptions || campaign.expansionSettings?.heptad || campaign.heptadOptions || campaign.settings?.heptad || {});
        const [view,setView] = useState('arena'), [selectedWeek,setSelectedWeek] = useState(null);
        const alliances = campaign.alliances || [], mine = alliances.find(alliance=>alliance.teamIds.includes(factionId));
        const factionOf = id => campaign.factions.find(faction=>faction.id===id) || App.DuatWorld?.factionById(id) || {id,name:id};
        const nameOf = id => alliances.find(alliance=>alliance.id===id)?.name || id;
        const slots = App.DuatCampaign.ROSTERS[App.DuatCampaign.settingsOf(campaign).roster].slots;
        const heptad = campaign.heptad, pinnacle = passedPinnacle === undefined ? campaign.pinnacle : passedPinnacle;
        const history = passedHistory || campaign.allianceHistory || campaign.dynasty?.allianceHistory || (campaign.dynasty?.seasons || []).flatMap(season=>Heptad.recordsForSeason({seasonId:`${campaign.id}:season:${season.cycle}`,seasonLabel:`Season ${season.cycle}`,alliances:season.alliances,heptad:season.heptad,completedWeeks:season.completedWeeks,pinnacle:season.pinnacle}));
        // Receipts are reconstructed only from completed weeks for older saves.
        const completedWeeks = useMemo(()=>(campaign.completedWeeks || []).map(week=> {
            if (week.allianceScores?.every(score=>Array.isArray(score.contributors))) return week;
            try { const receipts = Heptad.scoreWeek(alliances,week.factions,slots,options); return {...week,allianceScores:week.allianceScores.map(score=>{const receipt=receipts.find(r=>r.allianceId===score.allianceId);return receipt && receipt.total===score.total?{...score,...receipt}:score;})}; } catch (_) { return week; }
        }),[campaign.completedWeeks,alliances,slots,options.pool,options.duplicates,options.favorPoints]);
        const progression = Heptad.progress(alliances,heptad), myProgress = progression.find(alliance=>alliance.id===mine?.id);
        const snapshot = completedWeeks.find(week=>week.week===(selectedWeek || completedWeeks.at(-1)?.week));
        const myScore = snapshot?.allianceScores.find(score=>score.allianceId===mine?.id);
        const matches = heptad?.matches || [], records = Heptad.recordsForSeason({seasonId:passedSeasonId || `${campaign.id}:season:${campaign.dynastySeason || campaign.seasonNumber || 1}`,seasonLabel:`Season ${campaign.dynastySeason || campaign.seasonNumber || 1}`,alliances,heptad,completedWeeks,pinnacle});
        const gallery = heptad?.complete ? Heptad.archiveSeason(history,{seasonId:records[0]?.seasonId || 'Season 1',seasonLabel:records[0]?.seasonLabel,alliances,heptad,completedWeeks,pinnacle}) : history;
        if (!mine) return <p className="duat-notice">This faction is not entered in the {Heptad.tournamentName(campaign.alliances)} Games.</p>;
        return <div className="duat-heptad-experience"><nav className="duat-heptad-nav" aria-label={`${Heptad.tournamentName(alliances)} views`}>{[['arena','The arena'],['draw','The alliance draw'],['annals','Alliance annals']].map(([id,label])=><button key={id} aria-pressed={view===id} className={view===id?'selected':''} onClick={()=>setView(id)}>{label}</button>)}</nav>{view==='draw'?<Draw alliances={alliances} factionOf={factionOf} myId={mine.id}/>:view==='annals'?<Annals records={records} history={gallery} factionOf={factionOf}/>:<>
            <section className="duat-heptad-oath"><div><span className="duat-eyebrow">THE {Heptad.tournamentName(alliances).toUpperCase()} GAMES · {alliances.length} ALLIANCES</span><h2>Allies in a treacherous realm.</h2><p>One loss sends an alliance to redemption. A second ends its run. The unbeaten finalist must be defeated twice.</p><p className="duat-muted">{Heptad.describeOptions(options)}</p>{canManage && onAction && <NameAlliance alliance={mine} onAction={onAction} busy={busy} locked={completedWeeks.length > 0}/>}</div><Banner alliance={mine} factionOf={factionOf} large/></section>
            <div className="duat-heptad-situation"><div><span className="duat-eyebrow">YOUR POSITION</span><strong>{statusLabels[myProgress.status]}</strong><span>{myProgress.lives} {myProgress.lives===1?'life':'lives'} · Entry {mine.entry} · {myProgress.wins} {myProgress.wins===1?'win':'wins'}</span></div><div><span className="duat-eyebrow">{myProgress.next?'YOUR NEXT BATTLE':'THE ARENA'}</span>{myProgress.next ? <><strong>{nameOf(myProgress.next.homeId)} vs {nameOf(myProgress.next.awayId)}</strong><span>Week {myProgress.next.week} · {labels[myProgress.next.bracket]}</span></> : <><strong>{heptad?.championId?`${nameOf(heptad.championId)} holds the crown`:myProgress.status==='waiting'?`Your first battle begins in Week ${myProgress.entranceWeek}`:myProgress.status==='eliminated'?'Your alliance has left the arena':'Waiting for the next challenger'}</strong><span>{myProgress.status==='eliminated'?'Your faction’s all-play season continues.':'The full entrance order and paths are below.'}</span></>}</div></div>
            <section className="duat-heptad-entry-order" aria-label="Alliance progress">{progression.map(alliance=><div key={alliance.id} className={(alliance.id===mine.id?'is-mine ':'')+alliance.status}><span>{alliance.entry}</span><strong>{alliance.name}</strong><small>{statusLabels[alliance.status]} · {alliance.lives} {alliance.lives===1?'life':'lives'}</small></div>)}</section>
            <div className="duat-heptad-paths">{['top','bottom','final'].map(lane=>{const games=matches.filter(match=>lane==='final'?['championship','rematch'].includes(match.bracket):match.bracket===lane);const next=heptad?.next && (lane==='final'?['championship','rematch'].includes(heptad.next.bracket):heptad.next.bracket===lane)?heptad.next:null;return <section className="duat-panel" key={lane}><span className="duat-eyebrow">{lane==='top'?'I · KEEP THE ARENA':lane==='bottom'?'II · RETURN FROM DEFEAT':'III · EARN THE CROWN'}</span><h3>{lane==='final'?'The final alliances':labels[lane]}</h3>{games.map(match=><Match key={match.week+':'+match.bracket} match={match} nameOf={nameOf} myId={mine.id} completedWeeks={completedWeeks}/>)}{next && <div className="duat-heptad-up-next"><span>Next · Week {next.week}</span><strong>{nameOf(next.homeId)}<small>vs</small>{nameOf(next.awayId)}</strong></div>}{!games.length && !next && <p className="duat-muted">{lane==='bottom'?'The first defeated alliances arrive in Week 4.':lane==='final'?'The two paths meet here. The unbeaten side must lose twice.':'The first two entrants open the tournament in Week 2.'}</p>}</section>;})}</div>
            <section className="duat-panel duat-heptad-score-receipt"><div className="duat-panel-heading"><div><span className="duat-eyebrow">EVERY POINT HAS A NAME</span><h2>{snapshot?`${num(myScore?.total)} points · Week ${snapshot.week}`:'Your first score is still unwritten'}</h2></div>{completedWeeks.length>0 && <label className="duat-field">Completed week<select value={snapshot?.week || ''} onChange={event=>setSelectedWeek(Number(event.target.value))}>{completedWeeks.map(week=><option key={week.week} value={week.week}>Week {week.week}</option>)}</select></label>}</div>{myScore?.contributors?.length ? <><div className="duat-heptad-contributors">{myScore.contributors.map((player,index)=><article key={player.factionId+':'+player.playerId}><span className="duat-heptad-slot">{player.slot==='SUPER_FLEX'?'SFLEX':player.slot}</span><FactionMark faction={factionOf(player.factionId)}/><div><strong>{player.name}</strong><small>{factionOf(player.factionId).name}{player.season?` · ${player.season}`:''}{myScore.mvp?.playerId===player.playerId && myScore.mvp?.factionId===player.factionId?' · Alliance MVP':''}</small></div><span className="duat-heptad-points">{num(player.points)}{options.favorPoints && player.points!==player.basePoints && <small>{num(player.basePoints)} base</small>}</span></article>)}</div><div className="duat-heptad-member-totals">{(myScore.members || []).map(member=><span key={member.factionId}><strong>{factionOf(member.factionId).name}</strong>{member.counted} contributed · {num(member.points)} points</span>)}</div></> : <p>{snapshot?'This older result has no compatible player receipt; its original recorded total is preserved.':'After the first completed week, see the exact legal lineup, every contributing score and your alliance MVP.'}</p>}<p className="duat-muted">{Heptad.describeOptions(myScore?.options || options)}</p></section>
            {pinnacle && <Pinnacle pinnacle={pinnacle} campaign={campaign} factionId={factionId} nameOf={nameOf} factionOf={factionOf} onAction={canManage?onAction:null} busy={busy} completedWeeks={completedWeeks}/>}
        </>}</div>;
    }
    function AllianceIntro({campaign,factionId}) {
        const intro=App.DuatWeeklyFlow.allianceIntro(campaign,factionId);
        if(!intro)return <p className="duat-notice">This faction is not entered in the {Heptad.tournamentName(campaign.alliances)} Games.</p>;
        const factionOf=id=>campaign.factions.find(f=>f.id===id)||{id,name:id};
        return <section className="duat-panel duat-heptad-context duat-heptad-first-alliance">
            <span className="duat-eyebrow">YOUR ALLIANCE · THE {Heptad.tournamentName(campaign.alliances).toUpperCase()} GAMES</span><h2>{intro.alliance.name}</h2>
            <div className="duat-heptad-partners">{intro.alliance.teamIds.map(id=><div key={id}><FactionMark faction={factionOf(id)}/><strong>{factionOf(id).name}</strong><small>{id===factionId?'Your faction':'Your partner'}</small></div>)}</div>
            <p><strong>The Games begin in Week {intro.startWeek}.</strong> {intro.entryLabel} You were drawn as entrance {intro.entry} of {campaign.alliances.length}.</p>
            <p>Your alliance combines its best eligible players into one lineup. One loss sends you to redemption; a second ends your run. The unbeaten finalist must be beaten twice.</p>
            <p className="duat-muted">{Heptad.describeOptions(intro.options)}</p>
        </section>;
    }
    function WeeklyMatches({matches,week,tournament="Alliance"}) {
        return <div className="duat-heptad-week-scoreboards" aria-label={`${tournament} matches played in Week ${week}`}>
            {matches.length?matches.map(match=><article className={'duat-heptad-week-match'+(match.isMine?' is-mine':'')} key={match.bracket+':'+match.round+':'+match.homeId+':'+match.awayId}>
                <header><span className="duat-eyebrow">{match.pathLabel}</span>{match.isMine&&<span className="duat-heptad-your-match">Your match</span>}</header>
                {[[match.homeId,match.homeName,match.homeScore],[match.awayId,match.awayName,match.awayScore]].map(([id,name,points])=><div className={'duat-heptad-week-side'+(id===match.winnerId?' winner':'')} key={id}><span><strong>{name}</strong>{id===match.winnerId&&<small>Winner{match.tied?' · tiebreak':''}</small>}</span><strong className="duat-heptad-week-points">{num(points)}</strong></div>)}
                {match.tied&&<p className="duat-heptad-week-tie">Tied scores: {match.tieReason}</p>}
            </article>):<p className="duat-muted">No {tournament} matches were played in Week {week}.</p>}
        </div>;
    }
    function WeeklyRecap({campaign,factionId,week}) {
        const result=App.DuatWeeklyFlow.outcome(campaign,factionId,week),recap=result?.heptad;
        if(!recap)return <p className="duat-notice">{Heptad.tournamentName(campaign.alliances)} results appear after this week is played.</p>;
        if(!recap.alliance)return <section className="duat-panel duat-heptad-context"><span className="duat-eyebrow">WEEK {week} · THE {Heptad.tournamentName(campaign.alliances).toUpperCase()} GAMES</span><h2>This week in the arena</h2><WeeklyMatches matches={recap.matches||[]} week={week} tournament={Heptad.tournamentName(campaign.alliances)}/><p className="duat-notice">{recap.label}</p></section>;
        const factionOf=id=>campaign.factions.find(f=>f.id===id)||{id,name:id};
        return <section className={'duat-panel duat-heptad-context duat-heptad-weekly '+recap.status}>
            <span className="duat-eyebrow">WEEK {week} · THE {Heptad.tournamentName(campaign.alliances).toUpperCase()} GAMES</span><h2>This week in the arena</h2>
            <WeeklyMatches matches={recap.matches||[]} week={week} tournament={Heptad.tournamentName(campaign.alliances)}/>
            <div className="duat-heptad-own-week"><span className="duat-eyebrow">YOUR ALLIANCE</span><h3>{recap.label}</h3><p className="duat-heptad-context-name">{recap.alliance.name}</p></div>
            <p className="duat-heptad-context-lives"><strong>{statusLabels[recap.entryStatus]}</strong><span>{recap.lives} {recap.lives===1?'life':'lives'} remaining · {recap.wins}–{recap.losses} in the Games</span></p>
            {recap.next&&<p className="duat-heptad-context-next"><span>Next in the {Heptad.tournamentName(campaign.alliances)}</span><strong>{recap.next.label}</strong></p>}
            {recap.mvp&&<p className="duat-heptad-context-mvp"><span>Alliance MVP</span><strong>{recap.mvp.name}</strong> · {num(recap.mvp.points)} points · {factionOf(recap.mvp.factionId).name}</p>}
            {!!recap.contributors?.length&&<details className="duat-heptad-context-lineup"><summary>{num(recap.score.total)} best-ball points · {recap.contributors.length} contributors</summary><ol>{recap.contributors.map(p=><li key={p.factionId+':'+p.playerId}><span>{p.slot==='SUPER_FLEX'?'SFLEX':p.slot}</span><div><strong>{p.name}</strong><small>{factionOf(p.factionId).name}</small></div><strong>{num(p.points)}</strong></li>)}</ol><p className="duat-muted">{Heptad.describeOptions(recap.score.options || recap.options)}</p></details>}
            {result.pinnacle&&<div className="duat-heptad-context-pinnacle"><strong>Pinnacle {result.pinnacle.winnerId===recap.alliance.id?'victory':'defeat'}</strong><p>{result.pinnacle.tied?'The scores tied; the reigning alliance keeps the title.':result.pinnacle.defended?'The reigning alliance defended its title.':'The challenger won the optional title defense.'} Your original {Heptad.tournamentName(campaign.alliances)} result remains in the Annals.</p></div>}
        </section>;
    }
    App.DuatHeptadUI = { Games, RulesControls, Draw, Annals, AllianceIntro, WeeklyRecap, WeeklyMatches };
})();
