/* global React */
(function(root){
    'use strict';
    const App=root.App=root.App||{}, {useState,useEffect}=React;
    const Rituals=App.DuatRituals,Favors=App.DuatFavors;
    const base=location.pathname.includes('/dist-preview/')?'../':'';
    const portraitStyle=god=>({backgroundImage:`url("${base+god.art}")`,...(god.atlasIndex===null?{}:{backgroundSize:'300% 300%',backgroundPosition:`${god.atlasIndex%3*50}% ${Math.floor(god.atlasIndex/3)*50}%`})});
    function Portrait({god,className=''}){return <span className={'duat-divinity-portrait '+className} style={portraitStyle(god)} role="img" aria-label={`${god.name}, ${god.title}`}/>;}
    function DuatRitualsView({campaign,factionId,onAction,busy=false,ready=false,dirty=false,availablePlayers=[],lineup}){
        const faction=campaign.factions.find(f=>f.id===factionId),army=Rituals.activeArmy(faction);
        const sacred=campaign.phase==='season'&&Favors.SACRED_WEEKS.includes(campaign.week),preseason=campaign.phase==='season'&&campaign.week===1&&!campaign.completedWeeks.length,champion=campaign.phase==='complete'&&campaign.championId===factionId;
        const initialGod=champion?'amun':preseason?'mahdi':'kratos',initialChoice=champion?'amun':preseason?'summon-mahdi':'kratos-1';
        const r=faction.rituals||{},[godId,setGodId]=useState(initialGod),[choice,setChoice]=useState(initialChoice),[target,setTarget]=useState(''),[replacement,setReplacement]=useState(''),[position,setPosition]=useState('ALL'),[wager,setWager]=useState(10),[sourceWeek,setSourceWeek]=useState(1),[confirm,setConfirm]=useState(false);
        const god=Rituals.DEITIES.find(g=>g.id===godId),options=Rituals.CATALOG.filter(f=>f.deity===god.name),selected=options.find(f=>f.id===choice)||options[0];
        const declarations=faction.declaredFavors||r.declaredFavors||(faction.declaredFavor?[faction.declaredFavor]:[]);
        const reserved=Rituals.reservedBalance(faction),spare=faction.favorBalance-reserved;
        const starters=army?.players.filter(p=>(lineup||faction.lineup).includes(p.id))||[],buried=faction.armies.filter(a=>a.id!==army?.id&&!a.destroyed);
        const isWeekly=Favors.EXPANDED_FAVORS.some(f=>f.id===selected.id),throne=['amun','plutus'].includes(selected.id),preOnly=['anubis','shiva','summon-mahdi'].includes(selected.id);
        const windowOpen=throne?champion:preOnly?preseason:sacred;
        const locked=busy||ready||dirty||campaign.settings?.favors===false;
        const pending=r.pendingMahdi;
        const rosterFull=army&&army.players.length>=App.DuatCampaign.rosterSize(campaign);
        const openNow=option=>campaign.settings?.favors!==false&&(['amun','plutus'].includes(option.id)?champion:['anubis','shiva','summon-mahdi'].includes(option.id)?preseason:sacred);
        const guidance=campaign.settings?.favors===false?'Favors are turned off for this campaign.':preseason?'Before Week 1, summon Mahdi, call a buried player with Anubis, or awaken another ruler through Shiva. These rituals close when the first week is played.':champion?'The Throne Room is yours. Ask Amun for a recruit or Plutus to carry unspent favor into the next dynasty season.':campaign.phase==='complete'?'The Throne Room belongs to the reigning champion. The other gods return when the next dynasty begins.':sacred?`Sacred Week ${campaign.week}: reserve starter favors or invoke an available ritual before the week is played.`:'Starter favors and sacred rituals open in Weeks 5, 7, 10, 14, 15, 16 and 17.';
        useEffect(()=>{setGodId(initialGod);setChoice(initialChoice);setConfirm(false);},[campaign.phase,campaign.dynastySeason]);
        useEffect(()=>{setConfirm(false);setReplacement('');const first=isWeekly?starters[0]:selected.id==='amun'?availablePlayers[0]:army?.players[0];setTarget(first?.id||'');},[selected.id,army?.id]);
        function chooseGod(id){const g=Rituals.DEITIES.find(d=>d.id===id),choices=Rituals.CATALOG.filter(f=>f.deity===g.name);setGodId(id);setChoice((choices.find(openNow)||choices[0]).id);setConfirm(false);}
        function ritual(ritualId,fields={}){return onAction({type:'ritual',ritualId,factionId,...fields});}
        function invoke(){
            if(isWeekly)return onAction({type:'declare-favor',favorId:selected.id,playerId:target,...(selected.id==='janus-2'?{sourceWeek:campaign.week-1}:selected.id==='janus-3'?{sourceWeek}:{})});
            return ritual(selected.id,{playerId:target,replacementId:replacement,position,wager,confirmed:confirm});
        }
        let explanation=campaign.settings?.favors===false?'The founder turned favors off for this campaign.':windowOpen?'':throne?'The Throne Room opens to the reigning champion after Week 17.':preOnly?'This ritual opens after the excavation and before Week 1.':`The temple opens in sacred weeks 5, 7, 10, 14, 15, 16 and 17.`;
        const needsConfirmation=['midas','anubis','shiva'].includes(selected.id);
        const needsTarget=isWeekly||['midas','anubis','amun'].includes(selected.id);
        const targets=isWeekly?starters:selected.id==='amun'?availablePlayers:army?.players||[];
        const nextYearPoolLabel=selected.id==='amun'?'Choose your next army’s recruit':isWeekly?'Choose a starter':'Choose a player in your walking army';
        const offer=selected.id==='midas'&&target?(()=>{try{return Rituals.offeringValue(campaign,factionId,target);}catch{return null;}})():null;
        const currentReserved=declarations.find(d=>d.playerId===target)?.cost||0;
        const numericCost=typeof selected.cost==='number'?selected.cost:0;
        const affordable=isWeekly?numericCost<=spare+currentReserved:selected.id==='ebisu'?wager<=spare+(r.ebisu?.wager||0):true;
        return <div className="duat-divine-court">
            <section className="duat-panel duat-treasury"><div><span className="duat-eyebrow">{champion?'THE THRONE ROOM':'THE DIVINE TREASURY'}</span><h2>The gods remember every offering.</h2><p>{guidance}</p><p>One favor per starter. Several gods may answer in the same sacred week.</p></div><dl><div><dt>Remaining</dt><dd>{faction.favorBalance}</dd></div><div><dt>Reserved</dt><dd>{reserved}</dd></div><div><dt>Available</dt><dd>{spare}</dd></div></dl></section>
            <div className="duat-divinity-grid">{Rituals.DEITIES.map(g=><button key={g.id} className={'duat-divinity-card '+(g.id===godId?'selected':'')} aria-pressed={g.id===godId} onClick={()=>chooseGod(g.id)}><Portrait god={g}/><span><strong>{g.name}</strong><small>{g.title}</small>{Rituals.CATALOG.some(o=>o.deity===g.name&&openNow(o))&&<small className="duat-god-available">Available now</small>}</span></button>)}</div>
            <section className="duat-panel duat-ritual-chamber"><div className="duat-ritual-hero"><Portrait god={god}/><div><span className="duat-eyebrow">{selected.tier} · {selected.timing}</span><h2>{selected.name}</h2><p>{god.description}</p></div></div>
                <div className="duat-favor-tiers">{options.map(o=><button key={o.id} className={o.id===selected.id?'selected':''} onClick={()=>{setChoice(o.id);setConfirm(false);}}>{o.name}<strong>{typeof o.cost==='number'?(o.cost===0?'No offering':o.cost+' favor'):o.cost}</strong></button>)}</div>
                <p className="duat-ritual-effect">{selected.effect}</p>{selected.consequence&&<p className="duat-ritual-consequence">{selected.consequence}</p>}{selected.adaptation&&<details className="duat-ritual-adaptation"><summary>Historical campaign rule</summary><p>{selected.adaptation}</p></details>}
                {pending?<div className="duat-mahdi-reveal" role="status"><span className="duat-eyebrow">MAHDI HAS ANSWERED · D20 {pending.roll}</span><h3>{pending.player.name}</h3><p>{pending.player.position} · {pending.player.season} · {pending.rerolls?'Final draw':'One reroll remains'}</p><p>Your invocation is spent, even if you decline the recruit.</p>
                    <label className="duat-field">Make room in the walking army<select value={replacement} onChange={e=>{setReplacement(e.target.value);setConfirm(false);}} disabled={locked}><option value="">{rosterFull?'Choose a player to release':'Use an empty roster place'}</option>{army?.players.map(p=><option key={p.id} value={p.id}>Release {p.name}</option>)}</select></label>
                    {(replacement||pending.ritualId==='super-mahdi')&&<label className="duat-ritual-confirm"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)} disabled={locked}/>I accept {replacement?'the selected player leaving this army':''}{replacement&&pending.ritualId==='super-mahdi'?' and ':''}{pending.ritualId==='super-mahdi'?'the permanent loss of one random buried player':''}.</label>}
                    <div className="duat-actions"><button className="duat-button primary" disabled={locked||(rosterFull&&!replacement)||((replacement||pending.ritualId==='super-mahdi')&&!confirm)} onClick={()=>ritual('mahdi-accept',{replacementId:replacement,confirmed:confirm})}>Accept recruit</button><button className="duat-button" disabled={locked||pending.rerolls>=1||spare<20} onClick={()=>ritual('mahdi-reroll')}>Roll once more · 20 favor</button><button className="duat-link" disabled={locked} onClick={()=>ritual('mahdi-decline')}>Decline recruit</button></div></div>:
                    <div className="duat-ritual-controls">{needsTarget&&<label className="duat-field">{nextYearPoolLabel}<select value={target} onChange={e=>{setTarget(e.target.value);setConfirm(false);}} disabled={locked||!windowOpen}><option value="">Choose a player</option>{targets.map(p=><option key={p.id} value={p.id}>{p.name} · {p.position}{selected.id==='amun'?' · '+p.season:''}</option>)}</select></label>}
                        {selected.id==='anubis'&&<label className="duat-field">Call a player from a buried army<select value={replacement} onChange={e=>{setReplacement(e.target.value);setConfirm(false);}} disabled={locked||!windowOpen}><option value="">Choose a buried player</option>{buried.map(a=><optgroup key={a.id} label={a.rulerName||String(a.season)}>{a.players.map(p=><option key={p.id} value={p.id}>{p.name} · {p.position} · {p.season||a.season}</option>)}</optgroup>)}</select></label>}
                        {selected.id.startsWith('janus')&&<label className="duat-field">Remember a completed week<select value={selected.id==='janus-2'?campaign.week-1:sourceWeek} onChange={e=>setSourceWeek(Number(e.target.value))} disabled={locked||selected.id==='janus-2'}>{campaign.completedWeeks.map(w=><option key={w.week} value={w.week}>Week {w.week}</option>)}</select></label>}
                        {['mahdi','summon-mahdi','super-mahdi'].includes(selected.id)&&<label className="duat-field">Recruitment position<select value={position} onChange={e=>setPosition(e.target.value)} disabled={locked||!windowOpen}>{['ALL','QB','RB','WR','TE','FLEX'].map(p=><option key={p} value={p}>{p==='ALL'?'Any position':p}</option>)}</select></label>}
                        {selected.id==='ebisu'&&<div className="duat-ebisu-table">{Rituals.WAGERS.map(w=><button key={w.amount} className={w.amount===wager?'selected':''} aria-pressed={w.amount===wager} onClick={()=>setWager(w.amount)}><strong>{w.amount} points</strong><span>{w.chance*100}% win chance</span><small>{w.amount} favor reserved</small></button>)}</div>}
                        {offer&&<p className="duat-notice">{offer.label}</p>}
                        {needsConfirmation&&<label className="duat-ritual-confirm"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)} disabled={locked||!windowOpen}/>I understand this permanently {selected.id==='shiva'?'destroys the walking ruler and its army.':selected.id==='anubis'?'banishes the replaced player and removes the recruit from its buried army.':'sacrifices the chosen player.'}</label>}
                        {explanation&&<p className="duat-notice">{explanation}</p>}{dirty&&<p className="duat-notice">Save your lineup before calling on the gods.</p>}{ready&&<p className="duat-notice">Unready your faction to change an offering.</p>}
                        <div className="duat-actions"><button className={'duat-button '+(needsConfirmation?'danger':'primary')} disabled={locked||!windowOpen||!affordable||(needsTarget&&!target)||(selected.id==='anubis'&&!replacement)||(needsConfirmation&&!confirm)} onClick={invoke}>{isWeekly?(declarations.some(d=>d.playerId===target)?'Replace this starter’s favor':'Reserve favor'):`Invoke ${god.name}`}{numericCost?' · '+numericCost+' favor':''}</button>{selected.id==='ebisu'&&r.ebisu&&<button className="duat-link" disabled={locked} onClick={()=>ritual('ebisu-clear')}>Withdraw pending wager</button>}</div>
                    </div>}
            </section>
            {!!declarations.length&&<section className="duat-panel"><span className="duat-eyebrow">RESERVED FOR WEEK {campaign.week}</span><div className="duat-offering-list">{declarations.map(d=><div key={d.playerId}><div><strong>{Favors.getFavor(d.favorId,1)?.name}</strong><small>{army?.players.find(p=>p.id===d.playerId)?.name} · {d.cost} favor</small></div><button className="duat-link" disabled={locked} onClick={()=>onAction({type:'clear-favor',playerId:d.playerId})}>Remove</button></div>)}</div></section>}
            <section className="duat-panel"><span className="duat-eyebrow">THE LEDGER OF OFFERINGS</span><h2>Every bargain leaves a mark.</h2>{r.ledger?.length?<ol className="duat-ritual-ledger">{[...r.ledger].reverse().slice(0,30).map((e,i)=><li key={e.id||i}><span className="duat-ledger-stamp">S{e.cycle} · W{e.week}{e.roll?' · d20 '+e.roll:''}</span><strong>{e.message||Rituals.CATALOG.find(c=>c.id===e.ritualId)?.name||e.ritualId}</strong><small>{e.ritualId==='ebisu-result'?`${e.beforePoints} → ${e.afterPoints} faction points · `:''}{e.credit?'+'+e.credit+' favor ':''}{e.cost?'−'+e.cost+' favor':''}{e.carry?' · '+e.carry+' carried':''}</small></li>)}</ol>:<p className="duat-muted">Invocations, wagers, sacrifices and permanent consequences will be recorded here.</p>}
                {campaign.completedWeeks.some(w=>w.factions.find(f=>f.factionId===factionId)?.favors?.length)&&<details><summary>Completed starter favors</summary>{[...campaign.completedWeeks].reverse().map(w=>{const result=w.factions.find(f=>f.factionId===factionId);return(result?.favors||[]).map((e,i)=><p key={w.week+'-'+i}>Week {w.week} · {result.players.find(p=>p.id===e.playerId)?.name||'Starter'} · {e.name||Favors.getFavor(e.favorId,1)?.name} · {e.status==='applied'?`${e.beforePoints} → ${e.afterPoints} points (${e.delta>=0?'+':''}${e.delta}) · ${e.cost} favor`:`${e.reason} No favor spent.`}</p>);})}</details>}
            </section>
        </div>;
    }
    App.DuatDeityPortrait=Portrait;App.DuatRitualsView=DuatRitualsView;
})(typeof window!=='undefined'?window:globalThis);
